// Code generated by valforge. DO NOT EDIT.
// Version: v0.0.3
package valgen

import (
    "errors"
    "strings"
)

func ValidateEmail(email string) error {
	// Check if email is empty
	if email == "" {
		return errors.New("email cannot be empty")
	}

	// Check for spaces
	if strings.Contains(email, " ") {
		return errors.New("email cannot contain spaces")
	}

	// Check for exactly one @ symbol
	atIndex := strings.Index(email, "@")
	if atIndex == -1 {
		return errors.New("email must contain an @ symbol")
	}

	if atIndex != strings.LastIndex(email, "@") {
		return errors.New("email cannot contain multiple @ symbols")
	}

	// Split into local and domain parts
	localPart := email[:atIndex]
	domainPart := email[atIndex+1:]

	// Check local part isn't empty
	if localPart == "" {
		return errors.New("email must have a local part before the @ symbol")
	}

	// Check domain part isn't empty
	if domainPart == "" {
		return errors.New("email must have a domain part after the @ symbol")
	}

	// Check domain contains at least one dot
	if !strings.Contains(domainPart, ".") {
		return errors.New("domain must contain at least one dot")
	}

	// Check that dot isn't first or last character in domain
	if strings.HasPrefix(domainPart, ".") {
		return errors.New("domain cannot start with a dot")
	}

	if strings.HasSuffix(domainPart, ".") {
		return errors.New("domain cannot end with a dot")
	}

	// Check there's content after the last dot (TLD)
	lastDotIndex := strings.LastIndex(domainPart, ".")
	if lastDotIndex == len(domainPart)-1 {
		return errors.New("domain must have a TLD after the last dot")
	}

	return nil
}

