// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: degrees/v1/smtp_service.proto

/*
Package degreesv1 is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package degreesv1

import (
	"context"
	"errors"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	extDegreesv1 "github.com/richardbowden/degrees/internal/pb/degrees/v1"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var (
	_ codes.Code
	_ io.Reader
	_ status.Status
	_ = errors.New
	_ = runtime.String
	_ = utilities.NewDoubleArray
	_ = metadata.Join
)

func request_SMTPService_ConfigureSMTP_0(ctx context.Context, marshaler runtime.Marshaler, client extDegreesv1.SMTPServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq extDegreesv1.ConfigureSMTPRequest
		metadata runtime.ServerMetadata
	)
	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && !errors.Is(err, io.EOF) {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if req.Body != nil {
		_, _ = io.Copy(io.Discard, req.Body)
	}
	msg, err := client.ConfigureSMTP(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

func local_request_SMTPService_ConfigureSMTP_0(ctx context.Context, marshaler runtime.Marshaler, server extDegreesv1.SMTPServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq extDegreesv1.ConfigureSMTPRequest
		metadata runtime.ServerMetadata
	)
	if err := marshaler.NewDecoder(req.Body).Decode(&protoReq); err != nil && !errors.Is(err, io.EOF) {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	msg, err := server.ConfigureSMTP(ctx, &protoReq)
	return msg, metadata, err
}

func request_SMTPService_GetSMTPStatus_0(ctx context.Context, marshaler runtime.Marshaler, client extDegreesv1.SMTPServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq extDegreesv1.GetSMTPStatusRequest
		metadata runtime.ServerMetadata
	)
	if req.Body != nil {
		_, _ = io.Copy(io.Discard, req.Body)
	}
	msg, err := client.GetSMTPStatus(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

func local_request_SMTPService_GetSMTPStatus_0(ctx context.Context, marshaler runtime.Marshaler, server extDegreesv1.SMTPServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq extDegreesv1.GetSMTPStatusRequest
		metadata runtime.ServerMetadata
	)
	msg, err := server.GetSMTPStatus(ctx, &protoReq)
	return msg, metadata, err
}

// RegisterSMTPServiceHandlerServer registers the http handlers for service SMTPService to "mux".
// UnaryRPC     :call SMTPServiceServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterSMTPServiceHandlerFromEndpoint instead.
// GRPC interceptors will not work for this type of registration. To use interceptors, you must use the "runtime.WithMiddlewares" option in the "runtime.NewServeMux" call.
func RegisterSMTPServiceHandlerServer(ctx context.Context, mux *runtime.ServeMux, server extDegreesv1.SMTPServiceServer) error {
	mux.Handle(http.MethodPut, pattern_SMTPService_ConfigureSMTP_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/degrees.v1.SMTPService/ConfigureSMTP", runtime.WithHTTPPathPattern("/api/v1/admin/smtp/config"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_SMTPService_ConfigureSMTP_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_SMTPService_ConfigureSMTP_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodGet, pattern_SMTPService_GetSMTPStatus_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/degrees.v1.SMTPService/GetSMTPStatus", runtime.WithHTTPPathPattern("/api/v1/admin/smtp/status"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_SMTPService_GetSMTPStatus_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_SMTPService_GetSMTPStatus_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})

	return nil
}

// RegisterSMTPServiceHandlerFromEndpoint is same as RegisterSMTPServiceHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterSMTPServiceHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.NewClient(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Errorf("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Errorf("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()
	return RegisterSMTPServiceHandler(ctx, mux, conn)
}

// RegisterSMTPServiceHandler registers the http handlers for service SMTPService to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterSMTPServiceHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterSMTPServiceHandlerClient(ctx, mux, extDegreesv1.NewSMTPServiceClient(conn))
}

// RegisterSMTPServiceHandlerClient registers the http handlers for service SMTPService
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "extDegreesv1.SMTPServiceClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "extDegreesv1.SMTPServiceClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "extDegreesv1.SMTPServiceClient" to call the correct interceptors. This client ignores the HTTP middlewares.
func RegisterSMTPServiceHandlerClient(ctx context.Context, mux *runtime.ServeMux, client extDegreesv1.SMTPServiceClient) error {
	mux.Handle(http.MethodPut, pattern_SMTPService_ConfigureSMTP_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateContext(ctx, mux, req, "/degrees.v1.SMTPService/ConfigureSMTP", runtime.WithHTTPPathPattern("/api/v1/admin/smtp/config"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_SMTPService_ConfigureSMTP_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_SMTPService_ConfigureSMTP_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	mux.Handle(http.MethodGet, pattern_SMTPService_GetSMTPStatus_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateContext(ctx, mux, req, "/degrees.v1.SMTPService/GetSMTPStatus", runtime.WithHTTPPathPattern("/api/v1/admin/smtp/status"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_SMTPService_GetSMTPStatus_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_SMTPService_GetSMTPStatus_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	return nil
}

var (
	pattern_SMTPService_ConfigureSMTP_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3, 2, 4}, []string{"api", "v1", "admin", "smtp", "config"}, ""))
	pattern_SMTPService_GetSMTPStatus_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 2, 2, 2, 3, 2, 4}, []string{"api", "v1", "admin", "smtp", "status"}, ""))
)

var (
	forward_SMTPService_ConfigureSMTP_0 = runtime.ForwardResponseMessage
	forward_SMTPService_GetSMTPStatus_0 = runtime.ForwardResponseMessage
)
