// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: accounts.sql

package dbpg

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAccountEmailAddress = `-- name: AddAccountEmailAddress :exec
INSERT INTO email_addresses (email, account_id) 
VALUES ($1, $2)
`

type AddAccountEmailAddressParams struct {
	Email     string
	AccountID int64
}

func (q *Queries) AddAccountEmailAddress(ctx context.Context, arg AddAccountEmailAddressParams) error {
	_, err := q.db.Exec(ctx, addAccountEmailAddress, arg.Email, arg.AccountID)
	return err
}

const addAccountEmailValidationToken = `-- name: AddAccountEmailValidationToken :exec
INSERT INTO email_verification_code (account_id, code, expires_at) VALUES ($1, $2, $3)
`

type AddAccountEmailValidationTokenParams struct {
	AccountID int64
	Code      string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) AddAccountEmailValidationToken(ctx context.Context, arg AddAccountEmailValidationTokenParams) error {
	_, err := q.db.Exec(ctx, addAccountEmailValidationToken, arg.AccountID, arg.Code, arg.ExpiresAt)
	return err
}

const checkAccountActiveEmailExists = `-- name: CheckAccountActiveEmailExists :one
SELECT exists(select 1 from accounts where email = $1)
`

type CheckAccountActiveEmailExistsParams struct {
	Email string
}

func (q *Queries) CheckAccountActiveEmailExists(ctx context.Context, arg CheckAccountActiveEmailExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkAccountActiveEmailExists, arg.Email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (account_number, first_name, middle_name, surname, email, password_hash, acc_type)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING account_id, account_number, first_name, middle_name, surname, email, acc_type, sign_up_stage, password_hash, enabled, created_on, updated_at
`

type CreateAccountParams struct {
	AccountNumber string
	FirstName     string
	MiddleName    pgtype.Text
	Surname       pgtype.Text
	Email         string
	PasswordHash  string
	AccType       AccountType
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.AccountNumber,
		arg.FirstName,
		arg.MiddleName,
		arg.Surname,
		arg.Email,
		arg.PasswordHash,
		arg.AccType,
	)
	var i Account
	err := row.Scan(
		&i.AccountID,
		&i.AccountNumber,
		&i.FirstName,
		&i.MiddleName,
		&i.Surname,
		&i.Email,
		&i.AccType,
		&i.SignUpStage,
		&i.PasswordHash,
		&i.Enabled,
		&i.CreatedOn,
		&i.UpdatedAt,
	)
	return i, err
}
