// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalogue.sql

package dbpg

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO service_categories (name, slug, description, sort_order)
VALUES ($1, $2, $3, $4)
RETURNING id, name, slug, description, sort_order, created_at, updated_at
`

type CreateCategoryParams struct {
	Name        string
	Slug        string
	Description pgtype.Text
	SortOrder   int32
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (ServiceCategory, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.SortOrder,
	)
	var i ServiceCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createService = `-- name: CreateService :one
INSERT INTO services (
    category_id, name, slug, description, short_desc,
    base_price, duration_minutes, is_active, sort_order
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, category_id, name, slug, description, short_desc, base_price, duration_minutes, is_active, sort_order, created_at, updated_at
`

type CreateServiceParams struct {
	CategoryID      int64
	Name            string
	Slug            string
	Description     pgtype.Text
	ShortDesc       pgtype.Text
	BasePrice       int64
	DurationMinutes int32
	IsActive        bool
	SortOrder       int32
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.CategoryID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.ShortDesc,
		arg.BasePrice,
		arg.DurationMinutes,
		arg.IsActive,
		arg.SortOrder,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ShortDesc,
		&i.BasePrice,
		&i.DurationMinutes,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createServiceOption = `-- name: CreateServiceOption :one
INSERT INTO service_options (service_id, name, description, price, is_active, sort_order)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, service_id, name, description, price, is_active, sort_order, created_at
`

type CreateServiceOptionParams struct {
	ServiceID   int64
	Name        string
	Description pgtype.Text
	Price       int64
	IsActive    bool
	SortOrder   int32
}

func (q *Queries) CreateServiceOption(ctx context.Context, arg CreateServiceOptionParams) (ServiceOption, error) {
	row := q.db.QueryRow(ctx, createServiceOption,
		arg.ServiceID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.IsActive,
		arg.SortOrder,
	)
	var i ServiceOption
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const createVehicleCategory = `-- name: CreateVehicleCategory :one
INSERT INTO vehicle_categories (name, slug, description, sort_order)
VALUES ($1, $2, $3, $4)
RETURNING id, name, slug, description, sort_order, created_at, updated_at
`

type CreateVehicleCategoryParams struct {
	Name        string
	Slug        string
	Description pgtype.Text
	SortOrder   int32
}

func (q *Queries) CreateVehicleCategory(ctx context.Context, arg CreateVehicleCategoryParams) (VehicleCategory, error) {
	row := q.db.QueryRow(ctx, createVehicleCategory,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.SortOrder,
	)
	var i VehicleCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePriceTier = `-- name: DeletePriceTier :exec
DELETE FROM service_price_tiers
WHERE service_id = $1 AND vehicle_category_id = $2
`

type DeletePriceTierParams struct {
	ServiceID         int64
	VehicleCategoryID int64
}

func (q *Queries) DeletePriceTier(ctx context.Context, arg DeletePriceTierParams) error {
	_, err := q.db.Exec(ctx, deletePriceTier, arg.ServiceID, arg.VehicleCategoryID)
	return err
}

const deletePriceTiersByService = `-- name: DeletePriceTiersByService :exec
DELETE FROM service_price_tiers
WHERE service_id = $1
`

type DeletePriceTiersByServiceParams struct {
	ServiceID int64
}

func (q *Queries) DeletePriceTiersByService(ctx context.Context, arg DeletePriceTiersByServiceParams) error {
	_, err := q.db.Exec(ctx, deletePriceTiersByService, arg.ServiceID)
	return err
}

const deleteService = `-- name: DeleteService :one
UPDATE services
SET is_active = false
WHERE id = $1
RETURNING id, category_id, name, slug, description, short_desc, base_price, duration_minutes, is_active, sort_order, created_at, updated_at
`

type DeleteServiceParams struct {
	ID int64
}

func (q *Queries) DeleteService(ctx context.Context, arg DeleteServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, deleteService, arg.ID)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ShortDesc,
		&i.BasePrice,
		&i.DurationMinutes,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteServiceOption = `-- name: DeleteServiceOption :one
UPDATE service_options
SET is_active = false
WHERE id = $1
RETURNING id, service_id, name, description, price, is_active, sort_order, created_at
`

type DeleteServiceOptionParams struct {
	ID int64
}

func (q *Queries) DeleteServiceOption(ctx context.Context, arg DeleteServiceOptionParams) (ServiceOption, error) {
	row := q.db.QueryRow(ctx, deleteServiceOption, arg.ID)
	var i ServiceOption
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteVehicleCategory = `-- name: DeleteVehicleCategory :exec
DELETE FROM vehicle_categories
WHERE id = $1
`

type DeleteVehicleCategoryParams struct {
	ID int64
}

func (q *Queries) DeleteVehicleCategory(ctx context.Context, arg DeleteVehicleCategoryParams) error {
	_, err := q.db.Exec(ctx, deleteVehicleCategory, arg.ID)
	return err
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, name, slug, description, sort_order, created_at, updated_at FROM service_categories
WHERE slug = $1
`

type GetCategoryBySlugParams struct {
	Slug string
}

func (q *Queries) GetCategoryBySlug(ctx context.Context, arg GetCategoryBySlugParams) (ServiceCategory, error) {
	row := q.db.QueryRow(ctx, getCategoryBySlug, arg.Slug)
	var i ServiceCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPriceTier = `-- name: GetPriceTier :one
SELECT spt.id, spt.service_id, spt.vehicle_category_id, spt.price, spt.created_at,
       vc.name AS category_name, vc.slug AS category_slug
FROM service_price_tiers spt
JOIN vehicle_categories vc ON vc.id = spt.vehicle_category_id
WHERE spt.service_id = $1 AND spt.vehicle_category_id = $2
`

type GetPriceTierParams struct {
	ServiceID         int64
	VehicleCategoryID int64
}

type GetPriceTierRow struct {
	ID                int64
	ServiceID         int64
	VehicleCategoryID int64
	Price             int64
	CreatedAt         pgtype.Timestamptz
	CategoryName      string
	CategorySlug      string
}

func (q *Queries) GetPriceTier(ctx context.Context, arg GetPriceTierParams) (GetPriceTierRow, error) {
	row := q.db.QueryRow(ctx, getPriceTier, arg.ServiceID, arg.VehicleCategoryID)
	var i GetPriceTierRow
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.VehicleCategoryID,
		&i.Price,
		&i.CreatedAt,
		&i.CategoryName,
		&i.CategorySlug,
	)
	return i, err
}

const getServiceByID = `-- name: GetServiceByID :one
SELECT id, category_id, name, slug, description, short_desc, base_price, duration_minutes, is_active, sort_order, created_at, updated_at FROM services
WHERE id = $1
`

type GetServiceByIDParams struct {
	ID int64
}

func (q *Queries) GetServiceByID(ctx context.Context, arg GetServiceByIDParams) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceByID, arg.ID)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ShortDesc,
		&i.BasePrice,
		&i.DurationMinutes,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceBySlug = `-- name: GetServiceBySlug :one
SELECT s.id, s.category_id, s.name, s.slug, s.description, s.short_desc, s.base_price, s.duration_minutes, s.is_active, s.sort_order, s.created_at, s.updated_at, sc.name AS category_name
FROM services s
JOIN service_categories sc ON sc.id = s.category_id
WHERE s.slug = $1
`

type GetServiceBySlugParams struct {
	Slug string
}

type GetServiceBySlugRow struct {
	ID              int64
	CategoryID      int64
	Name            string
	Slug            string
	Description     pgtype.Text
	ShortDesc       pgtype.Text
	BasePrice       int64
	DurationMinutes int32
	IsActive        bool
	SortOrder       int32
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	CategoryName    string
}

func (q *Queries) GetServiceBySlug(ctx context.Context, arg GetServiceBySlugParams) (GetServiceBySlugRow, error) {
	row := q.db.QueryRow(ctx, getServiceBySlug, arg.Slug)
	var i GetServiceBySlugRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ShortDesc,
		&i.BasePrice,
		&i.DurationMinutes,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CategoryName,
	)
	return i, err
}

const getVehicleCategoryByID = `-- name: GetVehicleCategoryByID :one
SELECT id, name, slug, description, sort_order, created_at, updated_at FROM vehicle_categories
WHERE id = $1
`

type GetVehicleCategoryByIDParams struct {
	ID int64
}

func (q *Queries) GetVehicleCategoryByID(ctx context.Context, arg GetVehicleCategoryByIDParams) (VehicleCategory, error) {
	row := q.db.QueryRow(ctx, getVehicleCategoryByID, arg.ID)
	var i VehicleCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllServiceOptions = `-- name: ListAllServiceOptions :many
SELECT id, service_id, name, description, price, is_active, sort_order, created_at FROM service_options
WHERE service_id = $1
ORDER BY sort_order, name
`

type ListAllServiceOptionsParams struct {
	ServiceID int64
}

func (q *Queries) ListAllServiceOptions(ctx context.Context, arg ListAllServiceOptionsParams) ([]ServiceOption, error) {
	rows, err := q.db.Query(ctx, listAllServiceOptions, arg.ServiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceOption
	for rows.Next() {
		var i ServiceOption
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllServices = `-- name: ListAllServices :many
SELECT id, category_id, name, slug, description, short_desc, base_price, duration_minutes, is_active, sort_order, created_at, updated_at FROM services
ORDER BY sort_order, name
`

func (q *Queries) ListAllServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.Query(ctx, listAllServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ShortDesc,
			&i.BasePrice,
			&i.DurationMinutes,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, slug, description, sort_order, created_at, updated_at FROM service_categories
ORDER BY sort_order, name
`

func (q *Queries) ListCategories(ctx context.Context) ([]ServiceCategory, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceCategory
	for rows.Next() {
		var i ServiceCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPriceTiersByService = `-- name: ListPriceTiersByService :many

SELECT spt.id, spt.service_id, spt.vehicle_category_id, spt.price, spt.created_at,
       vc.name AS category_name, vc.slug AS category_slug
FROM service_price_tiers spt
JOIN vehicle_categories vc ON vc.id = spt.vehicle_category_id
WHERE spt.service_id = $1
ORDER BY vc.sort_order, vc.name
`

type ListPriceTiersByServiceParams struct {
	ServiceID int64
}

type ListPriceTiersByServiceRow struct {
	ID                int64
	ServiceID         int64
	VehicleCategoryID int64
	Price             int64
	CreatedAt         pgtype.Timestamptz
	CategoryName      string
	CategorySlug      string
}

// ========================================
// Service Price Tiers
// ========================================
func (q *Queries) ListPriceTiersByService(ctx context.Context, arg ListPriceTiersByServiceParams) ([]ListPriceTiersByServiceRow, error) {
	rows, err := q.db.Query(ctx, listPriceTiersByService, arg.ServiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPriceTiersByServiceRow
	for rows.Next() {
		var i ListPriceTiersByServiceRow
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.VehicleCategoryID,
			&i.Price,
			&i.CreatedAt,
			&i.CategoryName,
			&i.CategorySlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceOptions = `-- name: ListServiceOptions :many
SELECT id, service_id, name, description, price, is_active, sort_order, created_at FROM service_options
WHERE service_id = $1 AND is_active = true
ORDER BY sort_order, name
`

type ListServiceOptionsParams struct {
	ServiceID int64
}

func (q *Queries) ListServiceOptions(ctx context.Context, arg ListServiceOptionsParams) ([]ServiceOption, error) {
	rows, err := q.db.Query(ctx, listServiceOptions, arg.ServiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServiceOption
	for rows.Next() {
		var i ServiceOption
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServices = `-- name: ListServices :many
SELECT id, category_id, name, slug, description, short_desc, base_price, duration_minutes, is_active, sort_order, created_at, updated_at FROM services
WHERE is_active = true
ORDER BY sort_order, name
`

func (q *Queries) ListServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ShortDesc,
			&i.BasePrice,
			&i.DurationMinutes,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesByCategory = `-- name: ListServicesByCategory :many
SELECT id, category_id, name, slug, description, short_desc, base_price, duration_minutes, is_active, sort_order, created_at, updated_at FROM services
WHERE category_id = $1 AND is_active = true
ORDER BY sort_order, name
`

type ListServicesByCategoryParams struct {
	CategoryID int64
}

func (q *Queries) ListServicesByCategory(ctx context.Context, arg ListServicesByCategoryParams) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServicesByCategory, arg.CategoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.ShortDesc,
			&i.BasePrice,
			&i.DurationMinutes,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehicleCategories = `-- name: ListVehicleCategories :many

SELECT id, name, slug, description, sort_order, created_at, updated_at FROM vehicle_categories
ORDER BY sort_order, name
`

// ========================================
// Vehicle Categories
// ========================================
func (q *Queries) ListVehicleCategories(ctx context.Context) ([]VehicleCategory, error) {
	rows, err := q.db.Query(ctx, listVehicleCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VehicleCategory
	for rows.Next() {
		var i VehicleCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE service_categories
SET name = $2, slug = $3, description = $4, sort_order = $5
WHERE id = $1
RETURNING id, name, slug, description, sort_order, created_at, updated_at
`

type UpdateCategoryParams struct {
	ID          int64
	Name        string
	Slug        string
	Description pgtype.Text
	SortOrder   int32
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (ServiceCategory, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.SortOrder,
	)
	var i ServiceCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateService = `-- name: UpdateService :one
UPDATE services
SET category_id = $2, name = $3, slug = $4, description = $5,
    short_desc = $6, base_price = $7, duration_minutes = $8,
    is_active = $9, sort_order = $10
WHERE id = $1
RETURNING id, category_id, name, slug, description, short_desc, base_price, duration_minutes, is_active, sort_order, created_at, updated_at
`

type UpdateServiceParams struct {
	ID              int64
	CategoryID      int64
	Name            string
	Slug            string
	Description     pgtype.Text
	ShortDesc       pgtype.Text
	BasePrice       int64
	DurationMinutes int32
	IsActive        bool
	SortOrder       int32
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateService,
		arg.ID,
		arg.CategoryID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.ShortDesc,
		arg.BasePrice,
		arg.DurationMinutes,
		arg.IsActive,
		arg.SortOrder,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.ShortDesc,
		&i.BasePrice,
		&i.DurationMinutes,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateServiceOption = `-- name: UpdateServiceOption :one
UPDATE service_options
SET name = $2, description = $3, price = $4, is_active = $5, sort_order = $6
WHERE id = $1
RETURNING id, service_id, name, description, price, is_active, sort_order, created_at
`

type UpdateServiceOptionParams struct {
	ID          int64
	Name        string
	Description pgtype.Text
	Price       int64
	IsActive    bool
	SortOrder   int32
}

func (q *Queries) UpdateServiceOption(ctx context.Context, arg UpdateServiceOptionParams) (ServiceOption, error) {
	row := q.db.QueryRow(ctx, updateServiceOption,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.IsActive,
		arg.SortOrder,
	)
	var i ServiceOption
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const updateVehicleCategory = `-- name: UpdateVehicleCategory :one
UPDATE vehicle_categories
SET name = $2, slug = $3, description = $4, sort_order = $5
WHERE id = $1
RETURNING id, name, slug, description, sort_order, created_at, updated_at
`

type UpdateVehicleCategoryParams struct {
	ID          int64
	Name        string
	Slug        string
	Description pgtype.Text
	SortOrder   int32
}

func (q *Queries) UpdateVehicleCategory(ctx context.Context, arg UpdateVehicleCategoryParams) (VehicleCategory, error) {
	row := q.db.QueryRow(ctx, updateVehicleCategory,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.SortOrder,
	)
	var i VehicleCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPriceTier = `-- name: UpsertPriceTier :one
INSERT INTO service_price_tiers (service_id, vehicle_category_id, price)
VALUES ($1, $2, $3)
ON CONFLICT (service_id, vehicle_category_id)
DO UPDATE SET price = EXCLUDED.price
RETURNING id, service_id, vehicle_category_id, price, created_at
`

type UpsertPriceTierParams struct {
	ServiceID         int64
	VehicleCategoryID int64
	Price             int64
}

func (q *Queries) UpsertPriceTier(ctx context.Context, arg UpsertPriceTierParams) (ServicePriceTier, error) {
	row := q.db.QueryRow(ctx, upsertPriceTier, arg.ServiceID, arg.VehicleCategoryID, arg.Price)
	var i ServicePriceTier
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.VehicleCategoryID,
		&i.Price,
		&i.CreatedAt,
	)
	return i, err
}
