// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbpg

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type NotificationTemplate struct {
	ID         int64
	Name       string
	TemplateID int64
}

type OrgUserMembership struct {
	UserID         int64
	OrganizationID int64
	Role           string
	CreatedAt      pgtype.Timestamptz
}

type Organization struct {
	ID          int64
	Name        string
	Slug        string
	Description pgtype.Text
	Avatar      pgtype.Text
	Website     pgtype.Text
	IsActive    bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type Profile struct {
	UserID      int64
	DisplayName pgtype.Text
	Avatar      pgtype.Text
	Bio         pgtype.Text
	Website     pgtype.Text
	Location    pgtype.Text
	Company     pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Project struct {
	ID          int64
	OrgID       int64
	OwnerID     int64
	Name        string
	Slug        string
	Description pgtype.Text
	IsPrivate   bool
	IsArchived  bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type Setting struct {
	Key   string
	Value string
}

type Template struct {
	ID        int64
	Name      string
	Slug      string
	Content   string
	ScopeType string
	Version   int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	CreatedBy pgtype.Int8
	UpdatedBy pgtype.Int8
}

type User struct {
	ID             int64
	FirstName      string
	MiddleName     pgtype.Text
	Surname        pgtype.Text
	Username       string
	LoginEmail     string
	PrimaryEmailID int64
	SignUpStage    string
	PasswordHash   string
	Enabled        bool
	Sysop          bool
	CreatedOn      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type UserEmail struct {
	ID         int64
	UserID     int64
	Email      string
	IsVerified bool
	Enabled    bool
	CreatedOn  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Verification struct {
	ID        int64
	UserID    int64
	Token     string
	CreatedAt pgtype.Timestamptz
}
