// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password_reset.sql

package dbpg

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPasswordResetToken = `-- name: CreatePasswordResetToken :exec
INSERT INTO password_reset_tokens (
    token,
    user_id,
    expires_at,
    created_at)
VALUES ($1, $2, $3, $4)
`

type CreatePasswordResetTokenParams struct {
	Token     string
	UserID    int64
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error {
	_, err := q.db.Exec(ctx, createPasswordResetToken,
		arg.Token,
		arg.UserID,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiredPasswordResetTokens = `-- name: DeleteExpiredPasswordResetTokens :exec
DELETE FROM password_reset_tokens WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredPasswordResetTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredPasswordResetTokens)
	return err
}

const deletePasswordResetToken = `-- name: DeletePasswordResetToken :exec
DELETE FROM password_reset_tokens WHERE token = $1
`

type DeletePasswordResetTokenParams struct {
	Token string
}

func (q *Queries) DeletePasswordResetToken(ctx context.Context, arg DeletePasswordResetTokenParams) error {
	_, err := q.db.Exec(ctx, deletePasswordResetToken, arg.Token)
	return err
}

const deleteUserPasswordResetTokens = `-- name: DeleteUserPasswordResetTokens :exec
DELETE FROM password_reset_tokens WHERE user_id = $1
`

type DeleteUserPasswordResetTokensParams struct {
	UserID int64
}

func (q *Queries) DeleteUserPasswordResetTokens(ctx context.Context, arg DeleteUserPasswordResetTokensParams) error {
	_, err := q.db.Exec(ctx, deleteUserPasswordResetTokens, arg.UserID)
	return err
}

const getPasswordResetToken = `-- name: GetPasswordResetToken :one
SELECT id, user_id, token, expires_at, created_at FROM password_reset_tokens WHERE token = $1 AND expires_at > NOW()
`

type GetPasswordResetTokenParams struct {
	Token string
}

func (q *Queries) GetPasswordResetToken(ctx context.Context, arg GetPasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetToken, arg.Token)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
