// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package dbpg

import (
	"context"
)

const createSetting = `-- name: CreateSetting :exec
INSERT INTO setting
    (key, value)
 VALUES (
        $1, $2
         ) on conflict (key) do update set value = EXCLUDED.value
`

type CreateSettingParams struct {
	Key   string
	Value string
}

func (q *Queries) CreateSetting(ctx context.Context, arg CreateSettingParams) error {
	_, err := q.db.Exec(ctx, createSetting, arg.Key, arg.Value)
	return err
}

const getSetting = `-- name: GetSetting :one
select value from setting where key = $1
`

type GetSettingParams struct {
	Key string
}

func (q *Queries) GetSetting(ctx context.Context, arg GetSettingParams) (string, error) {
	row := q.db.QueryRow(ctx, getSetting, arg.Key)
	var value string
	err := row.Scan(&value)
	return value, err
}
