// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: templates.sql

package dbpg

import (
	"context"
)

const getTemplateByID = `-- name: GetTemplateByID :one
select id, name, slug, content, scope_type, version, created_at, updated_at, deleted_at, created_by, updated_by from template where id = $1
`

type GetTemplateByIDParams struct {
	ID int64
}

func (q *Queries) GetTemplateByID(ctx context.Context, arg GetTemplateByIDParams) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplateByID, arg.ID)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Content,
		&i.ScopeType,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getTemplateByName = `-- name: GetTemplateByName :one
SELECT content
FROM template
WHERE name = $1
  AND deleted_at IS NULL
ORDER BY version DESC
LIMIT 1
`

type GetTemplateByNameParams struct {
	Name string
}

func (q *Queries) GetTemplateByName(ctx context.Context, arg GetTemplateByNameParams) (string, error) {
	row := q.db.QueryRow(ctx, getTemplateByName, arg.Name)
	var content string
	err := row.Scan(&content)
	return content, err
}

const getTemplateBySystemName = `-- name: GetTemplateBySystemName :one
SELECT t.content
FROM notification_template nt
         JOIN template t on nt.template_id = t.id
WHERE nt.name = $1
`

type GetTemplateBySystemNameParams struct {
	Name string
}

func (q *Queries) GetTemplateBySystemName(ctx context.Context, arg GetTemplateBySystemNameParams) (string, error) {
	row := q.db.QueryRow(ctx, getTemplateBySystemName, arg.Name)
	var content string
	err := row.Scan(&content)
	return content, err
}

const listSystemNotificationTemplateNames = `-- name: ListSystemNotificationTemplateNames :many
select name from notification_template
`

func (q *Queries) ListSystemNotificationTemplateNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listSystemNotificationTemplateNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSystemNotificationTemplates = `-- name: ListSystemNotificationTemplates :many
select t.id, t.name, t.content,t.version, nt.name system_name
    from template t
         join notification_template nt on t.id = nt.id
`

type ListSystemNotificationTemplatesRow struct {
	ID         int64
	Name       string
	Content    string
	Version    int32
	SystemName string
}

func (q *Queries) ListSystemNotificationTemplates(ctx context.Context) ([]ListSystemNotificationTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listSystemNotificationTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSystemNotificationTemplatesRow
	for rows.Next() {
		var i ListSystemNotificationTemplatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Content,
			&i.Version,
			&i.SystemName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplates = `-- name: ListTemplates :many
SELECT id, name, slug, content, scope_type, version, created_at, updated_at, deleted_at, created_by, updated_by from template
`

func (q *Queries) ListTemplates(ctx context.Context) ([]Template, error) {
	rows, err := q.db.Query(ctx, listTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Content,
			&i.ScopeType,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
