// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: templates.sql

package dbpg

import (
	"context"
)

const getNotificationTemplateByName = `-- name: GetNotificationTemplateByName :one
SELECT t.content
FROM notification_template nt
         JOIN template t on nt.template_id = t.id
WHERE nt.name = $1
`

type GetNotificationTemplateByNameParams struct {
	Name string
}

func (q *Queries) GetNotificationTemplateByName(ctx context.Context, arg GetNotificationTemplateByNameParams) (string, error) {
	row := q.db.QueryRow(ctx, getNotificationTemplateByName, arg.Name)
	var content string
	err := row.Scan(&content)
	return content, err
}

const getTemplateByID = `-- name: GetTemplateByID :one
select id, name, ref, content, scope_type, version, created_at, updated_at, deleted_at, created_by, updated_by from template where id = $1
`

type GetTemplateByIDParams struct {
	ID int64
}

func (q *Queries) GetTemplateByID(ctx context.Context, arg GetTemplateByIDParams) (Template, error) {
	row := q.db.QueryRow(ctx, getTemplateByID, arg.ID)
	var i Template
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Ref,
		&i.Content,
		&i.ScopeType,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getTemplateByRef = `-- name: GetTemplateByRef :one
SELECT content
FROM template
WHERE ref = $1
  AND deleted_at IS NULL
ORDER BY version DESC
LIMIT 1
`

type GetTemplateByRefParams struct {
	Ref string
}

func (q *Queries) GetTemplateByRef(ctx context.Context, arg GetTemplateByRefParams) (string, error) {
	row := q.db.QueryRow(ctx, getTemplateByRef, arg.Ref)
	var content string
	err := row.Scan(&content)
	return content, err
}

const listSystemNotificationTemplates = `-- name: ListSystemNotificationTemplates :many

select t.id, t.name, t.content,t.version, nt.name system_name
    from template t
         join notification_template nt on t.id = nt.id
`

type ListSystemNotificationTemplatesRow struct {
	ID         int64
	Name       string
	Content    string
	Version    int32
	SystemName string
}

// -- name: ListSystemNotificationTemplates :many
// select name from notification_template;
func (q *Queries) ListSystemNotificationTemplates(ctx context.Context) ([]ListSystemNotificationTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listSystemNotificationTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSystemNotificationTemplatesRow
	for rows.Next() {
		var i ListSystemNotificationTemplatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Content,
			&i.Version,
			&i.SystemName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplates = `-- name: ListTemplates :many
SELECT id, name, ref, content, scope_type, version, created_at, updated_at, deleted_at, created_by, updated_by from template
`

func (q *Queries) ListTemplates(ctx context.Context) ([]Template, error) {
	rows, err := q.db.Query(ctx, listTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Ref,
			&i.Content,
			&i.ScopeType,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveTemplate = `-- name: SaveTemplate :exec
insert into template (name, ref, content, scope_type, version)
values ($1, $2, $3, $4, $5)
`

type SaveTemplateParams struct {
	Name      string
	Ref       string
	Content   string
	ScopeType string
	Version   int32
}

func (q *Queries) SaveTemplate(ctx context.Context, arg SaveTemplateParams) error {
	_, err := q.db.Exec(ctx, saveTemplate,
		arg.Name,
		arg.Ref,
		arg.Content,
		arg.ScopeType,
		arg.Version,
	)
	return err
}
