// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: verification.sql

package dbpg

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVerificationToken = `-- name: CreateVerificationToken :exec
INSERT INTO verification (
    token,
    user_id,
    created_at)
VALUES ($1, $2, $3)
`

type CreateVerificationTokenParams struct {
	Token     string
	UserID    int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateVerificationToken(ctx context.Context, arg CreateVerificationTokenParams) error {
	_, err := q.db.Exec(ctx, createVerificationToken, arg.Token, arg.UserID, arg.CreatedAt)
	return err
}

const deleteToken = `-- name: DeleteToken :exec
DELETE from verification where token = $1
`

type DeleteTokenParams struct {
	Token string
}

func (q *Queries) DeleteToken(ctx context.Context, arg DeleteTokenParams) error {
	_, err := q.db.Exec(ctx, deleteToken, arg.Token)
	return err
}

const getToken = `-- name: GetToken :one
SELECT id, user_id, token, created_at from verification where token = $1
`

type GetTokenParams struct {
	Token string
}

func (q *Queries) GetToken(ctx context.Context, arg GetTokenParams) (Verification, error) {
	row := q.db.QueryRow(ctx, getToken, arg.Token)
	var i Verification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.CreatedAt,
	)
	return i, err
}
