// Code generated by valforge. DO NOT EDIT.
// Version: v0.0.3

package services

import (

    valgen "github.com/typewriterco/p402/internal/valgen"
)

func (v LoginRequest) Validate() error {
    verr := valgen.NewValidationError("LoginRequest")

    if v.Email == "" {
        verr.AddFieldError("email", "email is required", v.Email)
    }
    err := valgen.ValidateEmail(v.Email)
    if err != nil {
        verr.AddFieldError("email", err.Error(), v.Email)
    }

    if v.Password == "" {
        verr.AddFieldError("password", "password is required", v.Password)
    }

    if len(verr.Errors) > 0 {
        return verr
    }

    return nil
}

