// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID           pgtype.Int8
	UserType     int32
	AccNum       string
	FirstName    string
	MiddleName   pgtype.Text
	Surname      pgtype.Text
	Email        string
	AccType      string
	CreatedOn    pgtype.Timestamptz
	LastUpdated  pgtype.Timestamptz
	SignUpStage  pgtype.Int4
	PasswordHash string
	Enabled      bool
}

type EmailAddress struct {
	Email      string
	AccID      uuid.UUID
	Verified   bool
	VerifiedOn pgtype.Timestamptz
}
