// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: degrees/v1/booking_service.proto

package degreesv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Booking struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId            int64                  `protobuf:"varint,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	VehicleId             int64                  `protobuf:"varint,3,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	ScheduledDate         string                 `protobuf:"bytes,4,opt,name=scheduled_date,json=scheduledDate,proto3" json:"scheduled_date,omitempty"`
	ScheduledTime         string                 `protobuf:"bytes,5,opt,name=scheduled_time,json=scheduledTime,proto3" json:"scheduled_time,omitempty"`
	EstimatedDurationMins int32                  `protobuf:"varint,6,opt,name=estimated_duration_mins,json=estimatedDurationMins,proto3" json:"estimated_duration_mins,omitempty"`
	Status                string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	PaymentStatus         string                 `protobuf:"bytes,8,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status,omitempty"`
	Subtotal              int64                  `protobuf:"varint,9,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	DepositAmount         int64                  `protobuf:"varint,10,opt,name=deposit_amount,json=depositAmount,proto3" json:"deposit_amount,omitempty"`
	TotalAmount           int64                  `protobuf:"varint,11,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Notes                 string                 `protobuf:"bytes,12,opt,name=notes,proto3" json:"notes,omitempty"`
	Services              []*BookingServiceItem  `protobuf:"bytes,13,rep,name=services,proto3" json:"services,omitempty"`
	Customer              *BookingCustomerInfo   `protobuf:"bytes,14,opt,name=customer,proto3" json:"customer,omitempty"`
	Vehicle               *BookingVehicleInfo    `protobuf:"bytes,15,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	CreatedAt             *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt             *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Booking) Reset() {
	*x = Booking{}
	mi := &file_degrees_v1_booking_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Booking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Booking) ProtoMessage() {}

func (x *Booking) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_booking_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Booking.ProtoReflect.Descriptor instead.
func (*Booking) Descriptor() ([]byte, []int) {
	return file_degrees_v1_booking_service_proto_rawDescGZIP(), []int{0}
}

func (x *Booking) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Booking) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *Booking) GetVehicleId() int64 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

func (x *Booking) GetScheduledDate() string {
	if x != nil {
		return x.ScheduledDate
	}
	return ""
}

func (x *Booking) GetScheduledTime() string {
	if x != nil {
		return x.ScheduledTime
	}
	return ""
}

func (x *Booking) GetEstimatedDurationMins() int32 {
	if x != nil {
		return x.EstimatedDurationMins
	}
	return 0
}

func (x *Booking) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Booking) GetPaymentStatus() string {
	if x != nil {
		return x.PaymentStatus
	}
	return ""
}

func (x *Booking) GetSubtotal() int64 {
	if x != nil {
		return x.Subtotal
	}
	return 0
}

func (x *Booking) GetDepositAmount() int64 {
	if x != nil {
		return x.DepositAmount
	}
	return 0
}

func (x *Booking) GetTotalAmount() int64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *Booking) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *Booking) GetServices() []*BookingServiceItem {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *Booking) GetCustomer() *BookingCustomerInfo {
	if x != nil {
		return x.Customer
	}
	return nil
}

func (x *Booking) GetVehicle() *BookingVehicleInfo {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

func (x *Booking) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Booking) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type BookingCustomerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingCustomerInfo) Reset() {
	*x = BookingCustomerInfo{}
	mi := &file_degrees_v1_booking_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingCustomerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingCustomerInfo) ProtoMessage() {}

func (x *BookingCustomerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_booking_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingCustomerInfo.ProtoReflect.Descriptor instead.
func (*BookingCustomerInfo) Descriptor() ([]byte, []int) {
	return file_degrees_v1_booking_service_proto_rawDescGZIP(), []int{1}
}

func (x *BookingCustomerInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BookingCustomerInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type BookingVehicleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Make          string                 `protobuf:"bytes,1,opt,name=make,proto3" json:"make,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Rego          string                 `protobuf:"bytes,3,opt,name=rego,proto3" json:"rego,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingVehicleInfo) Reset() {
	*x = BookingVehicleInfo{}
	mi := &file_degrees_v1_booking_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingVehicleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingVehicleInfo) ProtoMessage() {}

func (x *BookingVehicleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_booking_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingVehicleInfo.ProtoReflect.Descriptor instead.
func (*BookingVehicleInfo) Descriptor() ([]byte, []int) {
	return file_degrees_v1_booking_service_proto_rawDescGZIP(), []int{2}
}

func (x *BookingVehicleInfo) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *BookingVehicleInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *BookingVehicleInfo) GetRego() string {
	if x != nil {
		return x.Rego
	}
	return ""
}

type BookingServiceItem struct {
	state          protoimpl.MessageState      `protogen:"open.v1"`
	Id             int64                       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ServiceId      int64                       `protobuf:"varint,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ServiceName    string                      `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ServiceSlug    string                      `protobuf:"bytes,4,opt,name=service_slug,json=serviceSlug,proto3" json:"service_slug,omitempty"`
	PriceAtBooking int64                       `protobuf:"varint,5,opt,name=price_at_booking,json=priceAtBooking,proto3" json:"price_at_booking,omitempty"`
	Options        []*BookingServiceOptionItem `protobuf:"bytes,6,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BookingServiceItem) Reset() {
	*x = BookingServiceItem{}
	mi := &file_degrees_v1_booking_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingServiceItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingServiceItem) ProtoMessage() {}

func (x *BookingServiceItem) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_booking_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingServiceItem.ProtoReflect.Descriptor instead.
func (*BookingServiceItem) Descriptor() ([]byte, []int) {
	return file_degrees_v1_booking_service_proto_rawDescGZIP(), []int{3}
}

func (x *BookingServiceItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BookingServiceItem) GetServiceId() int64 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

func (x *BookingServiceItem) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *BookingServiceItem) GetServiceSlug() string {
	if x != nil {
		return x.ServiceSlug
	}
	return ""
}

func (x *BookingServiceItem) GetPriceAtBooking() int64 {
	if x != nil {
		return x.PriceAtBooking
	}
	return 0
}

func (x *BookingServiceItem) GetOptions() []*BookingServiceOptionItem {
	if x != nil {
		return x.Options
	}
	return nil
}

type BookingServiceOptionItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ServiceOptionId int64                  `protobuf:"varint,2,opt,name=service_option_id,json=serviceOptionId,proto3" json:"service_option_id,omitempty"`
	OptionName      string                 `protobuf:"bytes,3,opt,name=option_name,json=optionName,proto3" json:"option_name,omitempty"`
	PriceAtBooking  int64                  `protobuf:"varint,4,opt,name=price_at_booking,json=priceAtBooking,proto3" json:"price_at_booking,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BookingServiceOptionItem) Reset() {
	*x = BookingServiceOptionItem{}
	mi := &file_degrees_v1_booking_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingServiceOptionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingServiceOptionItem) ProtoMessage() {}

func (x *BookingServiceOptionItem) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_booking_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookingServiceOptionItem.ProtoReflect.Descriptor instead.
func (*BookingServiceOptionItem) Descriptor() ([]byte, []int) {
	return file_degrees_v1_booking_service_proto_rawDescGZIP(), []int{4}
}

func (x *BookingServiceOptionItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BookingServiceOptionItem) GetServiceOptionId() int64 {
	if x != nil {
		return x.ServiceOptionId
	}
	return 0
}

func (x *BookingServiceOptionItem) GetOptionName() string {
	if x != nil {
		return x.OptionName
	}
	return ""
}

func (x *BookingServiceOptionItem) GetPriceAtBooking() int64 {
	if x != nil {
		return x.PriceAtBooking
	}
	return 0
}

type AvailableSlot struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Date                  string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Time                  string                 `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	AvailableDurationMins int32                  `protobuf:"varint,3,opt,name=available_duration_mins,json=availableDurationMins,proto3" json:"available_duration_mins,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AvailableSlot) Reset() {
	*x = AvailableSlot{}
	mi := &file_degrees_v1_booking_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailableSlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableSlot) ProtoMessage() {}

func (x *AvailableSlot) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_booking_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableSlot.ProtoReflect.Descriptor instead.
func (*AvailableSlot) Descriptor() ([]byte, []int) {
	return file_degrees_v1_booking_service_proto_rawDescGZIP(), []int{5}
}

func (x *AvailableSlot) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *AvailableSlot) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

func (x *AvailableSlot) GetAvailableDurationMins() int32 {
	if x != nil {
		return x.AvailableDurationMins
	}
	return 0
}

type CreateBookingFromCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleId     int64                  `protobuf:"varint,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	ScheduledDate string                 `protobuf:"bytes,2,opt,name=scheduled_date,json=scheduledDate,proto3" json:"scheduled_date,omitempty"`
	ScheduledTime string                 `protobuf:"bytes,3,opt,name=scheduled_time,json=scheduledTime,proto3" json:"scheduled_time,omitempty"`
	Notes         string                 `protobuf:"bytes,4,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookingFromCartRequest) Reset() {
	*x = CreateBookingFromCartRequest{}
	mi := &file_degrees_v1_booking_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookingFromCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingFromCartRequest) ProtoMessage() {}

func (x *CreateBookingFromCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_booking_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingFromCartRequest.ProtoReflect.Descriptor instead.
func (*CreateBookingFromCartRequest) Descriptor() ([]byte, []int) {
	return file_degrees_v1_booking_service_proto_rawDescGZIP(), []int{6}
}

func (x *CreateBookingFromCartRequest) GetVehicleId() int64 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

func (x *CreateBookingFromCartRequest) GetScheduledDate() string {
	if x != nil {
		return x.ScheduledDate
	}
	return ""
}

func (x *CreateBookingFromCartRequest) GetScheduledTime() string {
	if x != nil {
		return x.ScheduledTime
	}
	return ""
}

func (x *CreateBookingFromCartRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type CreateBookingFromCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Booking       *Booking               `protobuf:"bytes,1,opt,name=booking,proto3" json:"booking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookingFromCartResponse) Reset() {
	*x = CreateBookingFromCartResponse{}
	mi := &file_degrees_v1_booking_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookingFromCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingFromCartResponse) ProtoMessage() {}

func (x *CreateBookingFromCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_booking_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingFromCartResponse.ProtoReflect.Descriptor instead.
func (*CreateBookingFromCartResponse) Descriptor() ([]byte, []int) {
	return file_degrees_v1_booking_service_proto_rawDescGZIP(), []int{7}
}

func (x *CreateBookingFromCartResponse) GetBooking() *Booking {
	if x != nil {
		return x.Booking
	}
	return nil
}

type GetAvailableSlotsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Date            string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	DurationMinutes int32                  `protobuf:"varint,2,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetAvailableSlotsRequest) Reset() {
	*x = GetAvailableSlotsRequest{}
	mi := &file_degrees_v1_booking_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableSlotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableSlotsRequest) ProtoMessage() {}

func (x *GetAvailableSlotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_booking_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableSlotsRequest.ProtoReflect.Descriptor instead.
func (*GetAvailableSlotsRequest) Descriptor() ([]byte, []int) {
	return file_degrees_v1_booking_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetAvailableSlotsRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetAvailableSlotsRequest) GetDurationMinutes() int32 {
	if x != nil {
		return x.DurationMinutes
	}
	return 0
}

type GetAvailableSlotsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slots         []*AvailableSlot       `protobuf:"bytes,1,rep,name=slots,proto3" json:"slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableSlotsResponse) Reset() {
	*x = GetAvailableSlotsResponse{}
	mi := &file_degrees_v1_booking_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableSlotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableSlotsResponse) ProtoMessage() {}

func (x *GetAvailableSlotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_booking_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableSlotsResponse.ProtoReflect.Descriptor instead.
func (*GetAvailableSlotsResponse) Descriptor() ([]byte, []int) {
	return file_degrees_v1_booking_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetAvailableSlotsResponse) GetSlots() []*AvailableSlot {
	if x != nil {
		return x.Slots
	}
	return nil
}

type ListMyBookingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyBookingsRequest) Reset() {
	*x = ListMyBookingsRequest{}
	mi := &file_degrees_v1_booking_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyBookingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyBookingsRequest) ProtoMessage() {}

func (x *ListMyBookingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_booking_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyBookingsRequest.ProtoReflect.Descriptor instead.
func (*ListMyBookingsRequest) Descriptor() ([]byte, []int) {
	return file_degrees_v1_booking_service_proto_rawDescGZIP(), []int{10}
}

type ListMyBookingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bookings      []*Booking             `protobuf:"bytes,1,rep,name=bookings,proto3" json:"bookings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyBookingsResponse) Reset() {
	*x = ListMyBookingsResponse{}
	mi := &file_degrees_v1_booking_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyBookingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyBookingsResponse) ProtoMessage() {}

func (x *ListMyBookingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_booking_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyBookingsResponse.ProtoReflect.Descriptor instead.
func (*ListMyBookingsResponse) Descriptor() ([]byte, []int) {
	return file_degrees_v1_booking_service_proto_rawDescGZIP(), []int{11}
}

func (x *ListMyBookingsResponse) GetBookings() []*Booking {
	if x != nil {
		return x.Bookings
	}
	return nil
}

type GetMyBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyBookingRequest) Reset() {
	*x = GetMyBookingRequest{}
	mi := &file_degrees_v1_booking_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyBookingRequest) ProtoMessage() {}

func (x *GetMyBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_booking_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyBookingRequest.ProtoReflect.Descriptor instead.
func (*GetMyBookingRequest) Descriptor() ([]byte, []int) {
	return file_degrees_v1_booking_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetMyBookingRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetMyBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Booking       *Booking               `protobuf:"bytes,1,opt,name=booking,proto3" json:"booking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyBookingResponse) Reset() {
	*x = GetMyBookingResponse{}
	mi := &file_degrees_v1_booking_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyBookingResponse) ProtoMessage() {}

func (x *GetMyBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_booking_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyBookingResponse.ProtoReflect.Descriptor instead.
func (*GetMyBookingResponse) Descriptor() ([]byte, []int) {
	return file_degrees_v1_booking_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetMyBookingResponse) GetBooking() *Booking {
	if x != nil {
		return x.Booking
	}
	return nil
}

type CancelBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBookingRequest) Reset() {
	*x = CancelBookingRequest{}
	mi := &file_degrees_v1_booking_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBookingRequest) ProtoMessage() {}

func (x *CancelBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_booking_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBookingRequest.ProtoReflect.Descriptor instead.
func (*CancelBookingRequest) Descriptor() ([]byte, []int) {
	return file_degrees_v1_booking_service_proto_rawDescGZIP(), []int{14}
}

func (x *CancelBookingRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CancelBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Booking       *Booking               `protobuf:"bytes,1,opt,name=booking,proto3" json:"booking,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBookingResponse) Reset() {
	*x = CancelBookingResponse{}
	mi := &file_degrees_v1_booking_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBookingResponse) ProtoMessage() {}

func (x *CancelBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_booking_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBookingResponse.ProtoReflect.Descriptor instead.
func (*CancelBookingResponse) Descriptor() ([]byte, []int) {
	return file_degrees_v1_booking_service_proto_rawDescGZIP(), []int{15}
}

func (x *CancelBookingResponse) GetBooking() *Booking {
	if x != nil {
		return x.Booking
	}
	return nil
}

func (x *CancelBookingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListAllBookingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DateFrom      string                 `protobuf:"bytes,1,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo        string                 `protobuf:"bytes,2,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllBookingsRequest) Reset() {
	*x = ListAllBookingsRequest{}
	mi := &file_degrees_v1_booking_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllBookingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllBookingsRequest) ProtoMessage() {}

func (x *ListAllBookingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_booking_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllBookingsRequest.ProtoReflect.Descriptor instead.
func (*ListAllBookingsRequest) Descriptor() ([]byte, []int) {
	return file_degrees_v1_booking_service_proto_rawDescGZIP(), []int{16}
}

func (x *ListAllBookingsRequest) GetDateFrom() string {
	if x != nil {
		return x.DateFrom
	}
	return ""
}

func (x *ListAllBookingsRequest) GetDateTo() string {
	if x != nil {
		return x.DateTo
	}
	return ""
}

type ListAllBookingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bookings      []*Booking             `protobuf:"bytes,1,rep,name=bookings,proto3" json:"bookings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllBookingsResponse) Reset() {
	*x = ListAllBookingsResponse{}
	mi := &file_degrees_v1_booking_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllBookingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllBookingsResponse) ProtoMessage() {}

func (x *ListAllBookingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_booking_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllBookingsResponse.ProtoReflect.Descriptor instead.
func (*ListAllBookingsResponse) Descriptor() ([]byte, []int) {
	return file_degrees_v1_booking_service_proto_rawDescGZIP(), []int{17}
}

func (x *ListAllBookingsResponse) GetBookings() []*Booking {
	if x != nil {
		return x.Bookings
	}
	return nil
}

type GetBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingRequest) Reset() {
	*x = GetBookingRequest{}
	mi := &file_degrees_v1_booking_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingRequest) ProtoMessage() {}

func (x *GetBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_booking_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingRequest.ProtoReflect.Descriptor instead.
func (*GetBookingRequest) Descriptor() ([]byte, []int) {
	return file_degrees_v1_booking_service_proto_rawDescGZIP(), []int{18}
}

func (x *GetBookingRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Booking       *Booking               `protobuf:"bytes,1,opt,name=booking,proto3" json:"booking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingResponse) Reset() {
	*x = GetBookingResponse{}
	mi := &file_degrees_v1_booking_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingResponse) ProtoMessage() {}

func (x *GetBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_booking_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingResponse.ProtoReflect.Descriptor instead.
func (*GetBookingResponse) Descriptor() ([]byte, []int) {
	return file_degrees_v1_booking_service_proto_rawDescGZIP(), []int{19}
}

func (x *GetBookingResponse) GetBooking() *Booking {
	if x != nil {
		return x.Booking
	}
	return nil
}

type UpdateBookingStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBookingStatusRequest) Reset() {
	*x = UpdateBookingStatusRequest{}
	mi := &file_degrees_v1_booking_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookingStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookingStatusRequest) ProtoMessage() {}

func (x *UpdateBookingStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_booking_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookingStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateBookingStatusRequest) Descriptor() ([]byte, []int) {
	return file_degrees_v1_booking_service_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateBookingStatusRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateBookingStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateBookingStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Booking       *Booking               `protobuf:"bytes,1,opt,name=booking,proto3" json:"booking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBookingStatusResponse) Reset() {
	*x = UpdateBookingStatusResponse{}
	mi := &file_degrees_v1_booking_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookingStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookingStatusResponse) ProtoMessage() {}

func (x *UpdateBookingStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_booking_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookingStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateBookingStatusResponse) Descriptor() ([]byte, []int) {
	return file_degrees_v1_booking_service_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateBookingStatusResponse) GetBooking() *Booking {
	if x != nil {
		return x.Booking
	}
	return nil
}

type CompleteBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Notes         string                 `protobuf:"bytes,2,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteBookingRequest) Reset() {
	*x = CompleteBookingRequest{}
	mi := &file_degrees_v1_booking_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteBookingRequest) ProtoMessage() {}

func (x *CompleteBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_booking_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteBookingRequest.ProtoReflect.Descriptor instead.
func (*CompleteBookingRequest) Descriptor() ([]byte, []int) {
	return file_degrees_v1_booking_service_proto_rawDescGZIP(), []int{22}
}

func (x *CompleteBookingRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CompleteBookingRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type CompleteBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Booking       *Booking               `protobuf:"bytes,1,opt,name=booking,proto3" json:"booking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteBookingResponse) Reset() {
	*x = CompleteBookingResponse{}
	mi := &file_degrees_v1_booking_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteBookingResponse) ProtoMessage() {}

func (x *CompleteBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_booking_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteBookingResponse.ProtoReflect.Descriptor instead.
func (*CompleteBookingResponse) Descriptor() ([]byte, []int) {
	return file_degrees_v1_booking_service_proto_rawDescGZIP(), []int{23}
}

func (x *CompleteBookingResponse) GetBooking() *Booking {
	if x != nil {
		return x.Booking
	}
	return nil
}

var File_degrees_v1_booking_service_proto protoreflect.FileDescriptor

const file_degrees_v1_booking_service_proto_rawDesc = "" +
	"\n" +
	" degrees/v1/booking_service.proto\x12\n" +
	"degrees.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc3\x05\n" +
	"\aBooking\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\x03R\n" +
	"customerId\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x03 \x01(\x03R\tvehicleId\x12%\n" +
	"\x0escheduled_date\x18\x04 \x01(\tR\rscheduledDate\x12%\n" +
	"\x0escheduled_time\x18\x05 \x01(\tR\rscheduledTime\x126\n" +
	"\x17estimated_duration_mins\x18\x06 \x01(\x05R\x15estimatedDurationMins\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12%\n" +
	"\x0epayment_status\x18\b \x01(\tR\rpaymentStatus\x12\x1a\n" +
	"\bsubtotal\x18\t \x01(\x03R\bsubtotal\x12%\n" +
	"\x0edeposit_amount\x18\n" +
	" \x01(\x03R\rdepositAmount\x12!\n" +
	"\ftotal_amount\x18\v \x01(\x03R\vtotalAmount\x12\x14\n" +
	"\x05notes\x18\f \x01(\tR\x05notes\x12:\n" +
	"\bservices\x18\r \x03(\v2\x1e.degrees.v1.BookingServiceItemR\bservices\x12;\n" +
	"\bcustomer\x18\x0e \x01(\v2\x1f.degrees.v1.BookingCustomerInfoR\bcustomer\x128\n" +
	"\avehicle\x18\x0f \x01(\v2\x1e.degrees.v1.BookingVehicleInfoR\avehicle\x129\n" +
	"\n" +
	"created_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"D\n" +
	"\x13BookingCustomerInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\"R\n" +
	"\x12BookingVehicleInfo\x12\x12\n" +
	"\x04make\x18\x01 \x01(\tR\x04make\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x12\x12\n" +
	"\x04rego\x18\x03 \x01(\tR\x04rego\"\xf3\x01\n" +
	"\x12BookingServiceItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\x03R\tserviceId\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12!\n" +
	"\fservice_slug\x18\x04 \x01(\tR\vserviceSlug\x12(\n" +
	"\x10price_at_booking\x18\x05 \x01(\x03R\x0epriceAtBooking\x12>\n" +
	"\aoptions\x18\x06 \x03(\v2$.degrees.v1.BookingServiceOptionItemR\aoptions\"\xa1\x01\n" +
	"\x18BookingServiceOptionItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12*\n" +
	"\x11service_option_id\x18\x02 \x01(\x03R\x0fserviceOptionId\x12\x1f\n" +
	"\voption_name\x18\x03 \x01(\tR\n" +
	"optionName\x12(\n" +
	"\x10price_at_booking\x18\x04 \x01(\x03R\x0epriceAtBooking\"o\n" +
	"\rAvailableSlot\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x12\n" +
	"\x04time\x18\x02 \x01(\tR\x04time\x126\n" +
	"\x17available_duration_mins\x18\x03 \x01(\x05R\x15availableDurationMins\"\xa1\x01\n" +
	"\x1cCreateBookingFromCartRequest\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\x03R\tvehicleId\x12%\n" +
	"\x0escheduled_date\x18\x02 \x01(\tR\rscheduledDate\x12%\n" +
	"\x0escheduled_time\x18\x03 \x01(\tR\rscheduledTime\x12\x14\n" +
	"\x05notes\x18\x04 \x01(\tR\x05notes\"N\n" +
	"\x1dCreateBookingFromCartResponse\x12-\n" +
	"\abooking\x18\x01 \x01(\v2\x13.degrees.v1.BookingR\abooking\"Y\n" +
	"\x18GetAvailableSlotsRequest\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12)\n" +
	"\x10duration_minutes\x18\x02 \x01(\x05R\x0fdurationMinutes\"L\n" +
	"\x19GetAvailableSlotsResponse\x12/\n" +
	"\x05slots\x18\x01 \x03(\v2\x19.degrees.v1.AvailableSlotR\x05slots\"\x17\n" +
	"\x15ListMyBookingsRequest\"I\n" +
	"\x16ListMyBookingsResponse\x12/\n" +
	"\bbookings\x18\x01 \x03(\v2\x13.degrees.v1.BookingR\bbookings\"%\n" +
	"\x13GetMyBookingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"E\n" +
	"\x14GetMyBookingResponse\x12-\n" +
	"\abooking\x18\x01 \x01(\v2\x13.degrees.v1.BookingR\abooking\"&\n" +
	"\x14CancelBookingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"`\n" +
	"\x15CancelBookingResponse\x12-\n" +
	"\abooking\x18\x01 \x01(\v2\x13.degrees.v1.BookingR\abooking\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"N\n" +
	"\x16ListAllBookingsRequest\x12\x1b\n" +
	"\tdate_from\x18\x01 \x01(\tR\bdateFrom\x12\x17\n" +
	"\adate_to\x18\x02 \x01(\tR\x06dateTo\"J\n" +
	"\x17ListAllBookingsResponse\x12/\n" +
	"\bbookings\x18\x01 \x03(\v2\x13.degrees.v1.BookingR\bbookings\"#\n" +
	"\x11GetBookingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"C\n" +
	"\x12GetBookingResponse\x12-\n" +
	"\abooking\x18\x01 \x01(\v2\x13.degrees.v1.BookingR\abooking\"D\n" +
	"\x1aUpdateBookingStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"L\n" +
	"\x1bUpdateBookingStatusResponse\x12-\n" +
	"\abooking\x18\x01 \x01(\v2\x13.degrees.v1.BookingR\abooking\">\n" +
	"\x16CompleteBookingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05notes\x18\x02 \x01(\tR\x05notes\"H\n" +
	"\x17CompleteBookingResponse\x12-\n" +
	"\abooking\x18\x01 \x01(\v2\x13.degrees.v1.BookingR\abooking2\xab\t\n" +
	"\x0eBookingService\x12\x89\x01\n" +
	"\x15CreateBookingFromCart\x12(.degrees.v1.CreateBookingFromCartRequest\x1a).degrees.v1.CreateBookingFromCartResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/api/v1/checkout\x12\x8a\x01\n" +
	"\x11GetAvailableSlots\x12$.degrees.v1.GetAvailableSlotsRequest\x1a%.degrees.v1.GetAvailableSlotsResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /api/v1/checkout/available-slots\x12t\n" +
	"\x0eListMyBookings\x12!.degrees.v1.ListMyBookingsRequest\x1a\".degrees.v1.ListMyBookingsResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/me/bookings\x12s\n" +
	"\fGetMyBooking\x12\x1f.degrees.v1.GetMyBookingRequest\x1a .degrees.v1.GetMyBookingResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/me/bookings/{id}\x12\x80\x01\n" +
	"\rCancelBooking\x12 .degrees.v1.CancelBookingRequest\x1a!.degrees.v1.CancelBookingResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/api/v1/me/bookings/{id}/cancel\x12z\n" +
	"\x0fListAllBookings\x12\".degrees.v1.ListAllBookingsRequest\x1a#.degrees.v1.ListAllBookingsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/api/v1/admin/bookings\x12p\n" +
	"\n" +
	"GetBooking\x12\x1d.degrees.v1.GetBookingRequest\x1a\x1e.degrees.v1.GetBookingResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/admin/bookings/{id}\x12\x95\x01\n" +
	"\x13UpdateBookingStatus\x12&.degrees.v1.UpdateBookingStatusRequest\x1a'.degrees.v1.UpdateBookingStatusResponse\"-\x82\xd3\xe4\x93\x02':\x01*\x1a\"/api/v1/admin/bookings/{id}/status\x12\x8b\x01\n" +
	"\x0fCompleteBooking\x12\".degrees.v1.CompleteBookingRequest\x1a#.degrees.v1.CompleteBookingResponse\"/\x82\xd3\xe4\x93\x02):\x01*\"$/api/v1/admin/bookings/{id}/completeB\xb1\x01\n" +
	"\x0ecom.degrees.v1B\x13BookingServiceProtoP\x01ZAgithub.com/richardbowden/degrees/internal/pb/degrees/v1;degreesv1\xa2\x02\x03DXX\xaa\x02\n" +
	"Degrees.V1\xca\x02\n" +
	"Degrees\\V1\xe2\x02\x16Degrees\\V1\\GPBMetadata\xea\x02\vDegrees::V1b\x06proto3"

var (
	file_degrees_v1_booking_service_proto_rawDescOnce sync.Once
	file_degrees_v1_booking_service_proto_rawDescData []byte
)

func file_degrees_v1_booking_service_proto_rawDescGZIP() []byte {
	file_degrees_v1_booking_service_proto_rawDescOnce.Do(func() {
		file_degrees_v1_booking_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_degrees_v1_booking_service_proto_rawDesc), len(file_degrees_v1_booking_service_proto_rawDesc)))
	})
	return file_degrees_v1_booking_service_proto_rawDescData
}

var file_degrees_v1_booking_service_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_degrees_v1_booking_service_proto_goTypes = []any{
	(*Booking)(nil),                       // 0: degrees.v1.Booking
	(*BookingCustomerInfo)(nil),           // 1: degrees.v1.BookingCustomerInfo
	(*BookingVehicleInfo)(nil),            // 2: degrees.v1.BookingVehicleInfo
	(*BookingServiceItem)(nil),            // 3: degrees.v1.BookingServiceItem
	(*BookingServiceOptionItem)(nil),      // 4: degrees.v1.BookingServiceOptionItem
	(*AvailableSlot)(nil),                 // 5: degrees.v1.AvailableSlot
	(*CreateBookingFromCartRequest)(nil),  // 6: degrees.v1.CreateBookingFromCartRequest
	(*CreateBookingFromCartResponse)(nil), // 7: degrees.v1.CreateBookingFromCartResponse
	(*GetAvailableSlotsRequest)(nil),      // 8: degrees.v1.GetAvailableSlotsRequest
	(*GetAvailableSlotsResponse)(nil),     // 9: degrees.v1.GetAvailableSlotsResponse
	(*ListMyBookingsRequest)(nil),         // 10: degrees.v1.ListMyBookingsRequest
	(*ListMyBookingsResponse)(nil),        // 11: degrees.v1.ListMyBookingsResponse
	(*GetMyBookingRequest)(nil),           // 12: degrees.v1.GetMyBookingRequest
	(*GetMyBookingResponse)(nil),          // 13: degrees.v1.GetMyBookingResponse
	(*CancelBookingRequest)(nil),          // 14: degrees.v1.CancelBookingRequest
	(*CancelBookingResponse)(nil),         // 15: degrees.v1.CancelBookingResponse
	(*ListAllBookingsRequest)(nil),        // 16: degrees.v1.ListAllBookingsRequest
	(*ListAllBookingsResponse)(nil),       // 17: degrees.v1.ListAllBookingsResponse
	(*GetBookingRequest)(nil),             // 18: degrees.v1.GetBookingRequest
	(*GetBookingResponse)(nil),            // 19: degrees.v1.GetBookingResponse
	(*UpdateBookingStatusRequest)(nil),    // 20: degrees.v1.UpdateBookingStatusRequest
	(*UpdateBookingStatusResponse)(nil),   // 21: degrees.v1.UpdateBookingStatusResponse
	(*CompleteBookingRequest)(nil),        // 22: degrees.v1.CompleteBookingRequest
	(*CompleteBookingResponse)(nil),       // 23: degrees.v1.CompleteBookingResponse
	(*timestamppb.Timestamp)(nil),         // 24: google.protobuf.Timestamp
}
var file_degrees_v1_booking_service_proto_depIdxs = []int32{
	3,  // 0: degrees.v1.Booking.services:type_name -> degrees.v1.BookingServiceItem
	1,  // 1: degrees.v1.Booking.customer:type_name -> degrees.v1.BookingCustomerInfo
	2,  // 2: degrees.v1.Booking.vehicle:type_name -> degrees.v1.BookingVehicleInfo
	24, // 3: degrees.v1.Booking.created_at:type_name -> google.protobuf.Timestamp
	24, // 4: degrees.v1.Booking.updated_at:type_name -> google.protobuf.Timestamp
	4,  // 5: degrees.v1.BookingServiceItem.options:type_name -> degrees.v1.BookingServiceOptionItem
	0,  // 6: degrees.v1.CreateBookingFromCartResponse.booking:type_name -> degrees.v1.Booking
	5,  // 7: degrees.v1.GetAvailableSlotsResponse.slots:type_name -> degrees.v1.AvailableSlot
	0,  // 8: degrees.v1.ListMyBookingsResponse.bookings:type_name -> degrees.v1.Booking
	0,  // 9: degrees.v1.GetMyBookingResponse.booking:type_name -> degrees.v1.Booking
	0,  // 10: degrees.v1.CancelBookingResponse.booking:type_name -> degrees.v1.Booking
	0,  // 11: degrees.v1.ListAllBookingsResponse.bookings:type_name -> degrees.v1.Booking
	0,  // 12: degrees.v1.GetBookingResponse.booking:type_name -> degrees.v1.Booking
	0,  // 13: degrees.v1.UpdateBookingStatusResponse.booking:type_name -> degrees.v1.Booking
	0,  // 14: degrees.v1.CompleteBookingResponse.booking:type_name -> degrees.v1.Booking
	6,  // 15: degrees.v1.BookingService.CreateBookingFromCart:input_type -> degrees.v1.CreateBookingFromCartRequest
	8,  // 16: degrees.v1.BookingService.GetAvailableSlots:input_type -> degrees.v1.GetAvailableSlotsRequest
	10, // 17: degrees.v1.BookingService.ListMyBookings:input_type -> degrees.v1.ListMyBookingsRequest
	12, // 18: degrees.v1.BookingService.GetMyBooking:input_type -> degrees.v1.GetMyBookingRequest
	14, // 19: degrees.v1.BookingService.CancelBooking:input_type -> degrees.v1.CancelBookingRequest
	16, // 20: degrees.v1.BookingService.ListAllBookings:input_type -> degrees.v1.ListAllBookingsRequest
	18, // 21: degrees.v1.BookingService.GetBooking:input_type -> degrees.v1.GetBookingRequest
	20, // 22: degrees.v1.BookingService.UpdateBookingStatus:input_type -> degrees.v1.UpdateBookingStatusRequest
	22, // 23: degrees.v1.BookingService.CompleteBooking:input_type -> degrees.v1.CompleteBookingRequest
	7,  // 24: degrees.v1.BookingService.CreateBookingFromCart:output_type -> degrees.v1.CreateBookingFromCartResponse
	9,  // 25: degrees.v1.BookingService.GetAvailableSlots:output_type -> degrees.v1.GetAvailableSlotsResponse
	11, // 26: degrees.v1.BookingService.ListMyBookings:output_type -> degrees.v1.ListMyBookingsResponse
	13, // 27: degrees.v1.BookingService.GetMyBooking:output_type -> degrees.v1.GetMyBookingResponse
	15, // 28: degrees.v1.BookingService.CancelBooking:output_type -> degrees.v1.CancelBookingResponse
	17, // 29: degrees.v1.BookingService.ListAllBookings:output_type -> degrees.v1.ListAllBookingsResponse
	19, // 30: degrees.v1.BookingService.GetBooking:output_type -> degrees.v1.GetBookingResponse
	21, // 31: degrees.v1.BookingService.UpdateBookingStatus:output_type -> degrees.v1.UpdateBookingStatusResponse
	23, // 32: degrees.v1.BookingService.CompleteBooking:output_type -> degrees.v1.CompleteBookingResponse
	24, // [24:33] is the sub-list for method output_type
	15, // [15:24] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_degrees_v1_booking_service_proto_init() }
func file_degrees_v1_booking_service_proto_init() {
	if File_degrees_v1_booking_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_degrees_v1_booking_service_proto_rawDesc), len(file_degrees_v1_booking_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_degrees_v1_booking_service_proto_goTypes,
		DependencyIndexes: file_degrees_v1_booking_service_proto_depIdxs,
		MessageInfos:      file_degrees_v1_booking_service_proto_msgTypes,
	}.Build()
	File_degrees_v1_booking_service_proto = out.File
	file_degrees_v1_booking_service_proto_goTypes = nil
	file_degrees_v1_booking_service_proto_depIdxs = nil
}
