// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: degrees/v1/history_service.proto

package degreesv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BookingId     int64                  `protobuf:"varint,2,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	CustomerId    int64                  `protobuf:"varint,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	VehicleId     int64                  `protobuf:"varint,4,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	CompletedDate *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=completed_date,json=completedDate,proto3" json:"completed_date,omitempty"`
	Notes         []*ServiceNote         `protobuf:"bytes,6,rep,name=notes,proto3" json:"notes,omitempty"`
	Products      []*ProductUsed         `protobuf:"bytes,7,rep,name=products,proto3" json:"products,omitempty"`
	Photos        []*ServicePhoto        `protobuf:"bytes,8,rep,name=photos,proto3" json:"photos,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceRecord) Reset() {
	*x = ServiceRecord{}
	mi := &file_degrees_v1_history_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRecord) ProtoMessage() {}

func (x *ServiceRecord) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_history_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRecord.ProtoReflect.Descriptor instead.
func (*ServiceRecord) Descriptor() ([]byte, []int) {
	return file_degrees_v1_history_service_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceRecord) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ServiceRecord) GetBookingId() int64 {
	if x != nil {
		return x.BookingId
	}
	return 0
}

func (x *ServiceRecord) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *ServiceRecord) GetVehicleId() int64 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

func (x *ServiceRecord) GetCompletedDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedDate
	}
	return nil
}

func (x *ServiceRecord) GetNotes() []*ServiceNote {
	if x != nil {
		return x.Notes
	}
	return nil
}

func (x *ServiceRecord) GetProducts() []*ProductUsed {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ServiceRecord) GetPhotos() []*ServicePhoto {
	if x != nil {
		return x.Photos
	}
	return nil
}

func (x *ServiceRecord) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ServiceRecord) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ServiceNote struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ServiceRecordId     int64                  `protobuf:"varint,2,opt,name=service_record_id,json=serviceRecordId,proto3" json:"service_record_id,omitempty"`
	NoteType            string                 `protobuf:"bytes,3,opt,name=note_type,json=noteType,proto3" json:"note_type,omitempty"`
	Content             string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	IsVisibleToCustomer bool                   `protobuf:"varint,5,opt,name=is_visible_to_customer,json=isVisibleToCustomer,proto3" json:"is_visible_to_customer,omitempty"`
	CreatedBy           int64                  `protobuf:"varint,6,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ServiceNote) Reset() {
	*x = ServiceNote{}
	mi := &file_degrees_v1_history_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceNote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceNote) ProtoMessage() {}

func (x *ServiceNote) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_history_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceNote.ProtoReflect.Descriptor instead.
func (*ServiceNote) Descriptor() ([]byte, []int) {
	return file_degrees_v1_history_service_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceNote) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ServiceNote) GetServiceRecordId() int64 {
	if x != nil {
		return x.ServiceRecordId
	}
	return 0
}

func (x *ServiceNote) GetNoteType() string {
	if x != nil {
		return x.NoteType
	}
	return ""
}

func (x *ServiceNote) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ServiceNote) GetIsVisibleToCustomer() bool {
	if x != nil {
		return x.IsVisibleToCustomer
	}
	return false
}

func (x *ServiceNote) GetCreatedBy() int64 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *ServiceNote) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ProductUsed struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ServiceRecordId int64                  `protobuf:"varint,2,opt,name=service_record_id,json=serviceRecordId,proto3" json:"service_record_id,omitempty"`
	ProductName     string                 `protobuf:"bytes,3,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Notes           string                 `protobuf:"bytes,4,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProductUsed) Reset() {
	*x = ProductUsed{}
	mi := &file_degrees_v1_history_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductUsed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductUsed) ProtoMessage() {}

func (x *ProductUsed) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_history_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductUsed.ProtoReflect.Descriptor instead.
func (*ProductUsed) Descriptor() ([]byte, []int) {
	return file_degrees_v1_history_service_proto_rawDescGZIP(), []int{2}
}

func (x *ProductUsed) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductUsed) GetServiceRecordId() int64 {
	if x != nil {
		return x.ServiceRecordId
	}
	return 0
}

func (x *ProductUsed) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *ProductUsed) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type ServicePhoto struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ServiceRecordId int64                  `protobuf:"varint,2,opt,name=service_record_id,json=serviceRecordId,proto3" json:"service_record_id,omitempty"`
	PhotoType       string                 `protobuf:"bytes,3,opt,name=photo_type,json=photoType,proto3" json:"photo_type,omitempty"`
	Url             string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Caption         string                 `protobuf:"bytes,5,opt,name=caption,proto3" json:"caption,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ServicePhoto) Reset() {
	*x = ServicePhoto{}
	mi := &file_degrees_v1_history_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServicePhoto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicePhoto) ProtoMessage() {}

func (x *ServicePhoto) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_history_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServicePhoto.ProtoReflect.Descriptor instead.
func (*ServicePhoto) Descriptor() ([]byte, []int) {
	return file_degrees_v1_history_service_proto_rawDescGZIP(), []int{3}
}

func (x *ServicePhoto) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ServicePhoto) GetServiceRecordId() int64 {
	if x != nil {
		return x.ServiceRecordId
	}
	return 0
}

func (x *ServicePhoto) GetPhotoType() string {
	if x != nil {
		return x.PhotoType
	}
	return ""
}

func (x *ServicePhoto) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ServicePhoto) GetCaption() string {
	if x != nil {
		return x.Caption
	}
	return ""
}

func (x *ServicePhoto) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListMyHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyHistoryRequest) Reset() {
	*x = ListMyHistoryRequest{}
	mi := &file_degrees_v1_history_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyHistoryRequest) ProtoMessage() {}

func (x *ListMyHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_history_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyHistoryRequest.ProtoReflect.Descriptor instead.
func (*ListMyHistoryRequest) Descriptor() ([]byte, []int) {
	return file_degrees_v1_history_service_proto_rawDescGZIP(), []int{4}
}

type ListMyHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*ServiceRecord       `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyHistoryResponse) Reset() {
	*x = ListMyHistoryResponse{}
	mi := &file_degrees_v1_history_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyHistoryResponse) ProtoMessage() {}

func (x *ListMyHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_history_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyHistoryResponse.ProtoReflect.Descriptor instead.
func (*ListMyHistoryResponse) Descriptor() ([]byte, []int) {
	return file_degrees_v1_history_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListMyHistoryResponse) GetRecords() []*ServiceRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type GetServiceRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceRecordRequest) Reset() {
	*x = GetServiceRecordRequest{}
	mi := &file_degrees_v1_history_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceRecordRequest) ProtoMessage() {}

func (x *GetServiceRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_history_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceRecordRequest.ProtoReflect.Descriptor instead.
func (*GetServiceRecordRequest) Descriptor() ([]byte, []int) {
	return file_degrees_v1_history_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetServiceRecordRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetServiceRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *ServiceRecord         `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceRecordResponse) Reset() {
	*x = GetServiceRecordResponse{}
	mi := &file_degrees_v1_history_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceRecordResponse) ProtoMessage() {}

func (x *GetServiceRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_history_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceRecordResponse.ProtoReflect.Descriptor instead.
func (*GetServiceRecordResponse) Descriptor() ([]byte, []int) {
	return file_degrees_v1_history_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetServiceRecordResponse) GetRecord() *ServiceRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

type ListCustomerHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCustomerHistoryRequest) Reset() {
	*x = ListCustomerHistoryRequest{}
	mi := &file_degrees_v1_history_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCustomerHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCustomerHistoryRequest) ProtoMessage() {}

func (x *ListCustomerHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_history_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCustomerHistoryRequest.ProtoReflect.Descriptor instead.
func (*ListCustomerHistoryRequest) Descriptor() ([]byte, []int) {
	return file_degrees_v1_history_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListCustomerHistoryRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListCustomerHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*ServiceRecord       `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCustomerHistoryResponse) Reset() {
	*x = ListCustomerHistoryResponse{}
	mi := &file_degrees_v1_history_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCustomerHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCustomerHistoryResponse) ProtoMessage() {}

func (x *ListCustomerHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_history_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCustomerHistoryResponse.ProtoReflect.Descriptor instead.
func (*ListCustomerHistoryResponse) Descriptor() ([]byte, []int) {
	return file_degrees_v1_history_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListCustomerHistoryResponse) GetRecords() []*ServiceRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type CreateServiceRecordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     int64                  `protobuf:"varint,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	CustomerId    int64                  `protobuf:"varint,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	VehicleId     int64                  `protobuf:"varint,3,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	CompletedDate *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=completed_date,json=completedDate,proto3" json:"completed_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServiceRecordRequest) Reset() {
	*x = CreateServiceRecordRequest{}
	mi := &file_degrees_v1_history_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServiceRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceRecordRequest) ProtoMessage() {}

func (x *CreateServiceRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_history_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceRecordRequest.ProtoReflect.Descriptor instead.
func (*CreateServiceRecordRequest) Descriptor() ([]byte, []int) {
	return file_degrees_v1_history_service_proto_rawDescGZIP(), []int{10}
}

func (x *CreateServiceRecordRequest) GetBookingId() int64 {
	if x != nil {
		return x.BookingId
	}
	return 0
}

func (x *CreateServiceRecordRequest) GetCustomerId() int64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *CreateServiceRecordRequest) GetVehicleId() int64 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

func (x *CreateServiceRecordRequest) GetCompletedDate() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedDate
	}
	return nil
}

type CreateServiceRecordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *ServiceRecord         `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServiceRecordResponse) Reset() {
	*x = CreateServiceRecordResponse{}
	mi := &file_degrees_v1_history_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServiceRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceRecordResponse) ProtoMessage() {}

func (x *CreateServiceRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_history_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceRecordResponse.ProtoReflect.Descriptor instead.
func (*CreateServiceRecordResponse) Descriptor() ([]byte, []int) {
	return file_degrees_v1_history_service_proto_rawDescGZIP(), []int{11}
}

func (x *CreateServiceRecordResponse) GetRecord() *ServiceRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

type AddServiceNoteRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NoteType            string                 `protobuf:"bytes,2,opt,name=note_type,json=noteType,proto3" json:"note_type,omitempty"`
	Content             string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	IsVisibleToCustomer bool                   `protobuf:"varint,4,opt,name=is_visible_to_customer,json=isVisibleToCustomer,proto3" json:"is_visible_to_customer,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AddServiceNoteRequest) Reset() {
	*x = AddServiceNoteRequest{}
	mi := &file_degrees_v1_history_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddServiceNoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddServiceNoteRequest) ProtoMessage() {}

func (x *AddServiceNoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_history_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddServiceNoteRequest.ProtoReflect.Descriptor instead.
func (*AddServiceNoteRequest) Descriptor() ([]byte, []int) {
	return file_degrees_v1_history_service_proto_rawDescGZIP(), []int{12}
}

func (x *AddServiceNoteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddServiceNoteRequest) GetNoteType() string {
	if x != nil {
		return x.NoteType
	}
	return ""
}

func (x *AddServiceNoteRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AddServiceNoteRequest) GetIsVisibleToCustomer() bool {
	if x != nil {
		return x.IsVisibleToCustomer
	}
	return false
}

type AddServiceNoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Note          *ServiceNote           `protobuf:"bytes,1,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddServiceNoteResponse) Reset() {
	*x = AddServiceNoteResponse{}
	mi := &file_degrees_v1_history_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddServiceNoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddServiceNoteResponse) ProtoMessage() {}

func (x *AddServiceNoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_history_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddServiceNoteResponse.ProtoReflect.Descriptor instead.
func (*AddServiceNoteResponse) Descriptor() ([]byte, []int) {
	return file_degrees_v1_history_service_proto_rawDescGZIP(), []int{13}
}

func (x *AddServiceNoteResponse) GetNote() *ServiceNote {
	if x != nil {
		return x.Note
	}
	return nil
}

type AddProductUsedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductName   string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Notes         string                 `protobuf:"bytes,3,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProductUsedRequest) Reset() {
	*x = AddProductUsedRequest{}
	mi := &file_degrees_v1_history_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProductUsedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductUsedRequest) ProtoMessage() {}

func (x *AddProductUsedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_history_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductUsedRequest.ProtoReflect.Descriptor instead.
func (*AddProductUsedRequest) Descriptor() ([]byte, []int) {
	return file_degrees_v1_history_service_proto_rawDescGZIP(), []int{14}
}

func (x *AddProductUsedRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AddProductUsedRequest) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *AddProductUsedRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type AddProductUsedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *ProductUsed           `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProductUsedResponse) Reset() {
	*x = AddProductUsedResponse{}
	mi := &file_degrees_v1_history_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProductUsedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductUsedResponse) ProtoMessage() {}

func (x *AddProductUsedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_history_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductUsedResponse.ProtoReflect.Descriptor instead.
func (*AddProductUsedResponse) Descriptor() ([]byte, []int) {
	return file_degrees_v1_history_service_proto_rawDescGZIP(), []int{15}
}

func (x *AddProductUsedResponse) GetProduct() *ProductUsed {
	if x != nil {
		return x.Product
	}
	return nil
}

var File_degrees_v1_history_service_proto protoreflect.FileDescriptor

const file_degrees_v1_history_service_proto_rawDesc = "" +
	"\n" +
	" degrees/v1/history_service.proto\x12\n" +
	"degrees.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcd\x03\n" +
	"\rServiceRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x02 \x01(\x03R\tbookingId\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\x03R\n" +
	"customerId\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x04 \x01(\x03R\tvehicleId\x12A\n" +
	"\x0ecompleted_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\rcompletedDate\x12-\n" +
	"\x05notes\x18\x06 \x03(\v2\x17.degrees.v1.ServiceNoteR\x05notes\x123\n" +
	"\bproducts\x18\a \x03(\v2\x17.degrees.v1.ProductUsedR\bproducts\x120\n" +
	"\x06photos\x18\b \x03(\v2\x18.degrees.v1.ServicePhotoR\x06photos\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x8f\x02\n" +
	"\vServiceNote\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12*\n" +
	"\x11service_record_id\x18\x02 \x01(\x03R\x0fserviceRecordId\x12\x1b\n" +
	"\tnote_type\x18\x03 \x01(\tR\bnoteType\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x123\n" +
	"\x16is_visible_to_customer\x18\x05 \x01(\bR\x13isVisibleToCustomer\x12\x1d\n" +
	"\n" +
	"created_by\x18\x06 \x01(\x03R\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x82\x01\n" +
	"\vProductUsed\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12*\n" +
	"\x11service_record_id\x18\x02 \x01(\x03R\x0fserviceRecordId\x12!\n" +
	"\fproduct_name\x18\x03 \x01(\tR\vproductName\x12\x14\n" +
	"\x05notes\x18\x04 \x01(\tR\x05notes\"\xd0\x01\n" +
	"\fServicePhoto\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12*\n" +
	"\x11service_record_id\x18\x02 \x01(\x03R\x0fserviceRecordId\x12\x1d\n" +
	"\n" +
	"photo_type\x18\x03 \x01(\tR\tphotoType\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x18\n" +
	"\acaption\x18\x05 \x01(\tR\acaption\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x16\n" +
	"\x14ListMyHistoryRequest\"L\n" +
	"\x15ListMyHistoryResponse\x123\n" +
	"\arecords\x18\x01 \x03(\v2\x19.degrees.v1.ServiceRecordR\arecords\")\n" +
	"\x17GetServiceRecordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"M\n" +
	"\x18GetServiceRecordResponse\x121\n" +
	"\x06record\x18\x01 \x01(\v2\x19.degrees.v1.ServiceRecordR\x06record\",\n" +
	"\x1aListCustomerHistoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"R\n" +
	"\x1bListCustomerHistoryResponse\x123\n" +
	"\arecords\x18\x01 \x03(\v2\x19.degrees.v1.ServiceRecordR\arecords\"\xbe\x01\n" +
	"\x1aCreateServiceRecordRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\x03R\tbookingId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\x03R\n" +
	"customerId\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x03 \x01(\x03R\tvehicleId\x12A\n" +
	"\x0ecompleted_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rcompletedDate\"P\n" +
	"\x1bCreateServiceRecordResponse\x121\n" +
	"\x06record\x18\x01 \x01(\v2\x19.degrees.v1.ServiceRecordR\x06record\"\x93\x01\n" +
	"\x15AddServiceNoteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tnote_type\x18\x02 \x01(\tR\bnoteType\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x123\n" +
	"\x16is_visible_to_customer\x18\x04 \x01(\bR\x13isVisibleToCustomer\"E\n" +
	"\x16AddServiceNoteResponse\x12+\n" +
	"\x04note\x18\x01 \x01(\v2\x17.degrees.v1.ServiceNoteR\x04note\"`\n" +
	"\x15AddProductUsedRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12\x14\n" +
	"\x05notes\x18\x03 \x01(\tR\x05notes\"K\n" +
	"\x16AddProductUsedResponse\x121\n" +
	"\aproduct\x18\x01 \x01(\v2\x17.degrees.v1.ProductUsedR\aproduct2\xb5\x06\n" +
	"\x0eHistoryService\x12p\n" +
	"\rListMyHistory\x12 .degrees.v1.ListMyHistoryRequest\x1a!.degrees.v1.ListMyHistoryResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/me/history\x12~\n" +
	"\x10GetServiceRecord\x12#.degrees.v1.GetServiceRecordRequest\x1a$.degrees.v1.GetServiceRecordResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/me/history/{id}\x12\x94\x01\n" +
	"\x13ListCustomerHistory\x12&.degrees.v1.ListCustomerHistoryRequest\x1a'.degrees.v1.ListCustomerHistoryResponse\",\x82\xd3\xe4\x93\x02&\x12$/api/v1/admin/customers/{id}/history\x12\x88\x01\n" +
	"\x13CreateServiceRecord\x12&.degrees.v1.CreateServiceRecordRequest\x1a'.degrees.v1.CreateServiceRecordResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/admin/records\x12\x84\x01\n" +
	"\x0eAddServiceNote\x12!.degrees.v1.AddServiceNoteRequest\x1a\".degrees.v1.AddServiceNoteResponse\"+\x82\xd3\xe4\x93\x02%:\x01*\" /api/v1/admin/records/{id}/notes\x12\x87\x01\n" +
	"\x0eAddProductUsed\x12!.degrees.v1.AddProductUsedRequest\x1a\".degrees.v1.AddProductUsedResponse\".\x82\xd3\xe4\x93\x02(:\x01*\"#/api/v1/admin/records/{id}/productsB\xb1\x01\n" +
	"\x0ecom.degrees.v1B\x13HistoryServiceProtoP\x01ZAgithub.com/richardbowden/degrees/internal/pb/degrees/v1;degreesv1\xa2\x02\x03DXX\xaa\x02\n" +
	"Degrees.V1\xca\x02\n" +
	"Degrees\\V1\xe2\x02\x16Degrees\\V1\\GPBMetadata\xea\x02\vDegrees::V1b\x06proto3"

var (
	file_degrees_v1_history_service_proto_rawDescOnce sync.Once
	file_degrees_v1_history_service_proto_rawDescData []byte
)

func file_degrees_v1_history_service_proto_rawDescGZIP() []byte {
	file_degrees_v1_history_service_proto_rawDescOnce.Do(func() {
		file_degrees_v1_history_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_degrees_v1_history_service_proto_rawDesc), len(file_degrees_v1_history_service_proto_rawDesc)))
	})
	return file_degrees_v1_history_service_proto_rawDescData
}

var file_degrees_v1_history_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_degrees_v1_history_service_proto_goTypes = []any{
	(*ServiceRecord)(nil),               // 0: degrees.v1.ServiceRecord
	(*ServiceNote)(nil),                 // 1: degrees.v1.ServiceNote
	(*ProductUsed)(nil),                 // 2: degrees.v1.ProductUsed
	(*ServicePhoto)(nil),                // 3: degrees.v1.ServicePhoto
	(*ListMyHistoryRequest)(nil),        // 4: degrees.v1.ListMyHistoryRequest
	(*ListMyHistoryResponse)(nil),       // 5: degrees.v1.ListMyHistoryResponse
	(*GetServiceRecordRequest)(nil),     // 6: degrees.v1.GetServiceRecordRequest
	(*GetServiceRecordResponse)(nil),    // 7: degrees.v1.GetServiceRecordResponse
	(*ListCustomerHistoryRequest)(nil),  // 8: degrees.v1.ListCustomerHistoryRequest
	(*ListCustomerHistoryResponse)(nil), // 9: degrees.v1.ListCustomerHistoryResponse
	(*CreateServiceRecordRequest)(nil),  // 10: degrees.v1.CreateServiceRecordRequest
	(*CreateServiceRecordResponse)(nil), // 11: degrees.v1.CreateServiceRecordResponse
	(*AddServiceNoteRequest)(nil),       // 12: degrees.v1.AddServiceNoteRequest
	(*AddServiceNoteResponse)(nil),      // 13: degrees.v1.AddServiceNoteResponse
	(*AddProductUsedRequest)(nil),       // 14: degrees.v1.AddProductUsedRequest
	(*AddProductUsedResponse)(nil),      // 15: degrees.v1.AddProductUsedResponse
	(*timestamppb.Timestamp)(nil),       // 16: google.protobuf.Timestamp
}
var file_degrees_v1_history_service_proto_depIdxs = []int32{
	16, // 0: degrees.v1.ServiceRecord.completed_date:type_name -> google.protobuf.Timestamp
	1,  // 1: degrees.v1.ServiceRecord.notes:type_name -> degrees.v1.ServiceNote
	2,  // 2: degrees.v1.ServiceRecord.products:type_name -> degrees.v1.ProductUsed
	3,  // 3: degrees.v1.ServiceRecord.photos:type_name -> degrees.v1.ServicePhoto
	16, // 4: degrees.v1.ServiceRecord.created_at:type_name -> google.protobuf.Timestamp
	16, // 5: degrees.v1.ServiceRecord.updated_at:type_name -> google.protobuf.Timestamp
	16, // 6: degrees.v1.ServiceNote.created_at:type_name -> google.protobuf.Timestamp
	16, // 7: degrees.v1.ServicePhoto.created_at:type_name -> google.protobuf.Timestamp
	0,  // 8: degrees.v1.ListMyHistoryResponse.records:type_name -> degrees.v1.ServiceRecord
	0,  // 9: degrees.v1.GetServiceRecordResponse.record:type_name -> degrees.v1.ServiceRecord
	0,  // 10: degrees.v1.ListCustomerHistoryResponse.records:type_name -> degrees.v1.ServiceRecord
	16, // 11: degrees.v1.CreateServiceRecordRequest.completed_date:type_name -> google.protobuf.Timestamp
	0,  // 12: degrees.v1.CreateServiceRecordResponse.record:type_name -> degrees.v1.ServiceRecord
	1,  // 13: degrees.v1.AddServiceNoteResponse.note:type_name -> degrees.v1.ServiceNote
	2,  // 14: degrees.v1.AddProductUsedResponse.product:type_name -> degrees.v1.ProductUsed
	4,  // 15: degrees.v1.HistoryService.ListMyHistory:input_type -> degrees.v1.ListMyHistoryRequest
	6,  // 16: degrees.v1.HistoryService.GetServiceRecord:input_type -> degrees.v1.GetServiceRecordRequest
	8,  // 17: degrees.v1.HistoryService.ListCustomerHistory:input_type -> degrees.v1.ListCustomerHistoryRequest
	10, // 18: degrees.v1.HistoryService.CreateServiceRecord:input_type -> degrees.v1.CreateServiceRecordRequest
	12, // 19: degrees.v1.HistoryService.AddServiceNote:input_type -> degrees.v1.AddServiceNoteRequest
	14, // 20: degrees.v1.HistoryService.AddProductUsed:input_type -> degrees.v1.AddProductUsedRequest
	5,  // 21: degrees.v1.HistoryService.ListMyHistory:output_type -> degrees.v1.ListMyHistoryResponse
	7,  // 22: degrees.v1.HistoryService.GetServiceRecord:output_type -> degrees.v1.GetServiceRecordResponse
	9,  // 23: degrees.v1.HistoryService.ListCustomerHistory:output_type -> degrees.v1.ListCustomerHistoryResponse
	11, // 24: degrees.v1.HistoryService.CreateServiceRecord:output_type -> degrees.v1.CreateServiceRecordResponse
	13, // 25: degrees.v1.HistoryService.AddServiceNote:output_type -> degrees.v1.AddServiceNoteResponse
	15, // 26: degrees.v1.HistoryService.AddProductUsed:output_type -> degrees.v1.AddProductUsedResponse
	21, // [21:27] is the sub-list for method output_type
	15, // [15:21] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_degrees_v1_history_service_proto_init() }
func file_degrees_v1_history_service_proto_init() {
	if File_degrees_v1_history_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_degrees_v1_history_service_proto_rawDesc), len(file_degrees_v1_history_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_degrees_v1_history_service_proto_goTypes,
		DependencyIndexes: file_degrees_v1_history_service_proto_depIdxs,
		MessageInfos:      file_degrees_v1_history_service_proto_msgTypes,
	}.Build()
	File_degrees_v1_history_service_proto = out.File
	file_degrees_v1_history_service_proto_goTypes = nil
	file_degrees_v1_history_service_proto_depIdxs = nil
}
