// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: degrees/v1/history_service.proto

package degreesv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HistoryService_ListMyHistory_FullMethodName       = "/degrees.v1.HistoryService/ListMyHistory"
	HistoryService_GetServiceRecord_FullMethodName    = "/degrees.v1.HistoryService/GetServiceRecord"
	HistoryService_ListCustomerHistory_FullMethodName = "/degrees.v1.HistoryService/ListCustomerHistory"
	HistoryService_CreateServiceRecord_FullMethodName = "/degrees.v1.HistoryService/CreateServiceRecord"
	HistoryService_AddServiceNote_FullMethodName      = "/degrees.v1.HistoryService/AddServiceNote"
	HistoryService_AddProductUsed_FullMethodName      = "/degrees.v1.HistoryService/AddProductUsed"
)

// HistoryServiceClient is the client API for HistoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HistoryServiceClient interface {
	// List service history for the authenticated user
	ListMyHistory(ctx context.Context, in *ListMyHistoryRequest, opts ...grpc.CallOption) (*ListMyHistoryResponse, error)
	// Get a specific service record
	GetServiceRecord(ctx context.Context, in *GetServiceRecordRequest, opts ...grpc.CallOption) (*GetServiceRecordResponse, error)
	// List history for a specific customer (admin)
	ListCustomerHistory(ctx context.Context, in *ListCustomerHistoryRequest, opts ...grpc.CallOption) (*ListCustomerHistoryResponse, error)
	// Create a service record (admin)
	CreateServiceRecord(ctx context.Context, in *CreateServiceRecordRequest, opts ...grpc.CallOption) (*CreateServiceRecordResponse, error)
	// Add a note to a service record (admin)
	AddServiceNote(ctx context.Context, in *AddServiceNoteRequest, opts ...grpc.CallOption) (*AddServiceNoteResponse, error)
	// Add a product used to a service record (admin)
	AddProductUsed(ctx context.Context, in *AddProductUsedRequest, opts ...grpc.CallOption) (*AddProductUsedResponse, error)
}

type historyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHistoryServiceClient(cc grpc.ClientConnInterface) HistoryServiceClient {
	return &historyServiceClient{cc}
}

func (c *historyServiceClient) ListMyHistory(ctx context.Context, in *ListMyHistoryRequest, opts ...grpc.CallOption) (*ListMyHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMyHistoryResponse)
	err := c.cc.Invoke(ctx, HistoryService_ListMyHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyServiceClient) GetServiceRecord(ctx context.Context, in *GetServiceRecordRequest, opts ...grpc.CallOption) (*GetServiceRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServiceRecordResponse)
	err := c.cc.Invoke(ctx, HistoryService_GetServiceRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyServiceClient) ListCustomerHistory(ctx context.Context, in *ListCustomerHistoryRequest, opts ...grpc.CallOption) (*ListCustomerHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCustomerHistoryResponse)
	err := c.cc.Invoke(ctx, HistoryService_ListCustomerHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyServiceClient) CreateServiceRecord(ctx context.Context, in *CreateServiceRecordRequest, opts ...grpc.CallOption) (*CreateServiceRecordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateServiceRecordResponse)
	err := c.cc.Invoke(ctx, HistoryService_CreateServiceRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyServiceClient) AddServiceNote(ctx context.Context, in *AddServiceNoteRequest, opts ...grpc.CallOption) (*AddServiceNoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddServiceNoteResponse)
	err := c.cc.Invoke(ctx, HistoryService_AddServiceNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historyServiceClient) AddProductUsed(ctx context.Context, in *AddProductUsedRequest, opts ...grpc.CallOption) (*AddProductUsedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddProductUsedResponse)
	err := c.cc.Invoke(ctx, HistoryService_AddProductUsed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HistoryServiceServer is the server API for HistoryService service.
// All implementations should embed UnimplementedHistoryServiceServer
// for forward compatibility.
type HistoryServiceServer interface {
	// List service history for the authenticated user
	ListMyHistory(context.Context, *ListMyHistoryRequest) (*ListMyHistoryResponse, error)
	// Get a specific service record
	GetServiceRecord(context.Context, *GetServiceRecordRequest) (*GetServiceRecordResponse, error)
	// List history for a specific customer (admin)
	ListCustomerHistory(context.Context, *ListCustomerHistoryRequest) (*ListCustomerHistoryResponse, error)
	// Create a service record (admin)
	CreateServiceRecord(context.Context, *CreateServiceRecordRequest) (*CreateServiceRecordResponse, error)
	// Add a note to a service record (admin)
	AddServiceNote(context.Context, *AddServiceNoteRequest) (*AddServiceNoteResponse, error)
	// Add a product used to a service record (admin)
	AddProductUsed(context.Context, *AddProductUsedRequest) (*AddProductUsedResponse, error)
}

// UnimplementedHistoryServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHistoryServiceServer struct{}

func (UnimplementedHistoryServiceServer) ListMyHistory(context.Context, *ListMyHistoryRequest) (*ListMyHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMyHistory not implemented")
}
func (UnimplementedHistoryServiceServer) GetServiceRecord(context.Context, *GetServiceRecordRequest) (*GetServiceRecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServiceRecord not implemented")
}
func (UnimplementedHistoryServiceServer) ListCustomerHistory(context.Context, *ListCustomerHistoryRequest) (*ListCustomerHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCustomerHistory not implemented")
}
func (UnimplementedHistoryServiceServer) CreateServiceRecord(context.Context, *CreateServiceRecordRequest) (*CreateServiceRecordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateServiceRecord not implemented")
}
func (UnimplementedHistoryServiceServer) AddServiceNote(context.Context, *AddServiceNoteRequest) (*AddServiceNoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddServiceNote not implemented")
}
func (UnimplementedHistoryServiceServer) AddProductUsed(context.Context, *AddProductUsedRequest) (*AddProductUsedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddProductUsed not implemented")
}
func (UnimplementedHistoryServiceServer) testEmbeddedByValue() {}

// UnsafeHistoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HistoryServiceServer will
// result in compilation errors.
type UnsafeHistoryServiceServer interface {
	mustEmbedUnimplementedHistoryServiceServer()
}

func RegisterHistoryServiceServer(s grpc.ServiceRegistrar, srv HistoryServiceServer) {
	// If the following call panics, it indicates UnimplementedHistoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HistoryService_ServiceDesc, srv)
}

func _HistoryService_ListMyHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).ListMyHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryService_ListMyHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).ListMyHistory(ctx, req.(*ListMyHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryService_GetServiceRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).GetServiceRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryService_GetServiceRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).GetServiceRecord(ctx, req.(*GetServiceRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryService_ListCustomerHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCustomerHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).ListCustomerHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryService_ListCustomerHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).ListCustomerHistory(ctx, req.(*ListCustomerHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryService_CreateServiceRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateServiceRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).CreateServiceRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryService_CreateServiceRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).CreateServiceRecord(ctx, req.(*CreateServiceRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryService_AddServiceNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddServiceNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).AddServiceNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryService_AddServiceNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).AddServiceNote(ctx, req.(*AddServiceNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistoryService_AddProductUsed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProductUsedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryServiceServer).AddProductUsed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryService_AddProductUsed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryServiceServer).AddProductUsed(ctx, req.(*AddProductUsedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HistoryService_ServiceDesc is the grpc.ServiceDesc for HistoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HistoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "degrees.v1.HistoryService",
	HandlerType: (*HistoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListMyHistory",
			Handler:    _HistoryService_ListMyHistory_Handler,
		},
		{
			MethodName: "GetServiceRecord",
			Handler:    _HistoryService_GetServiceRecord_Handler,
		},
		{
			MethodName: "ListCustomerHistory",
			Handler:    _HistoryService_ListCustomerHistory_Handler,
		},
		{
			MethodName: "CreateServiceRecord",
			Handler:    _HistoryService_CreateServiceRecord_Handler,
		},
		{
			MethodName: "AddServiceNote",
			Handler:    _HistoryService_AddServiceNote_Handler,
		},
		{
			MethodName: "AddProductUsed",
			Handler:    _HistoryService_AddProductUsed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "degrees/v1/history_service.proto",
}
