// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: degrees/v1/payment_service.proto

package degreesv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDepositSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     int64                  `protobuf:"varint,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDepositSessionRequest) Reset() {
	*x = CreateDepositSessionRequest{}
	mi := &file_degrees_v1_payment_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDepositSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDepositSessionRequest) ProtoMessage() {}

func (x *CreateDepositSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_payment_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDepositSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateDepositSessionRequest) Descriptor() ([]byte, []int) {
	return file_degrees_v1_payment_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDepositSessionRequest) GetBookingId() int64 {
	if x != nil {
		return x.BookingId
	}
	return 0
}

type CreateDepositSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientSecret  string                 `protobuf:"bytes,1,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	DepositAmount int64                  `protobuf:"varint,2,opt,name=deposit_amount,json=depositAmount,proto3" json:"deposit_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDepositSessionResponse) Reset() {
	*x = CreateDepositSessionResponse{}
	mi := &file_degrees_v1_payment_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDepositSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDepositSessionResponse) ProtoMessage() {}

func (x *CreateDepositSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_payment_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDepositSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateDepositSessionResponse) Descriptor() ([]byte, []int) {
	return file_degrees_v1_payment_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDepositSessionResponse) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *CreateDepositSessionResponse) GetDepositAmount() int64 {
	if x != nil {
		return x.DepositAmount
	}
	return 0
}

var File_degrees_v1_payment_service_proto protoreflect.FileDescriptor

const file_degrees_v1_payment_service_proto_rawDesc = "" +
	"\n" +
	" degrees/v1/payment_service.proto\x12\n" +
	"degrees.v1\x1a\x1cgoogle/api/annotations.proto\"<\n" +
	"\x1bCreateDepositSessionRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\x03R\tbookingId\"j\n" +
	"\x1cCreateDepositSessionResponse\x12#\n" +
	"\rclient_secret\x18\x01 \x01(\tR\fclientSecret\x12%\n" +
	"\x0edeposit_amount\x18\x02 \x01(\x03R\rdepositAmount2\xa1\x01\n" +
	"\x0ePaymentService\x12\x8e\x01\n" +
	"\x14CreateDepositSession\x12'.degrees.v1.CreateDepositSessionRequest\x1a(.degrees.v1.CreateDepositSessionResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/v1/checkout/depositB\xb1\x01\n" +
	"\x0ecom.degrees.v1B\x13PaymentServiceProtoP\x01ZAgithub.com/richardbowden/degrees/internal/pb/degrees/v1;degreesv1\xa2\x02\x03DXX\xaa\x02\n" +
	"Degrees.V1\xca\x02\n" +
	"Degrees\\V1\xe2\x02\x16Degrees\\V1\\GPBMetadata\xea\x02\vDegrees::V1b\x06proto3"

var (
	file_degrees_v1_payment_service_proto_rawDescOnce sync.Once
	file_degrees_v1_payment_service_proto_rawDescData []byte
)

func file_degrees_v1_payment_service_proto_rawDescGZIP() []byte {
	file_degrees_v1_payment_service_proto_rawDescOnce.Do(func() {
		file_degrees_v1_payment_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_degrees_v1_payment_service_proto_rawDesc), len(file_degrees_v1_payment_service_proto_rawDesc)))
	})
	return file_degrees_v1_payment_service_proto_rawDescData
}

var file_degrees_v1_payment_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_degrees_v1_payment_service_proto_goTypes = []any{
	(*CreateDepositSessionRequest)(nil),  // 0: degrees.v1.CreateDepositSessionRequest
	(*CreateDepositSessionResponse)(nil), // 1: degrees.v1.CreateDepositSessionResponse
}
var file_degrees_v1_payment_service_proto_depIdxs = []int32{
	0, // 0: degrees.v1.PaymentService.CreateDepositSession:input_type -> degrees.v1.CreateDepositSessionRequest
	1, // 1: degrees.v1.PaymentService.CreateDepositSession:output_type -> degrees.v1.CreateDepositSessionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_degrees_v1_payment_service_proto_init() }
func file_degrees_v1_payment_service_proto_init() {
	if File_degrees_v1_payment_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_degrees_v1_payment_service_proto_rawDesc), len(file_degrees_v1_payment_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_degrees_v1_payment_service_proto_goTypes,
		DependencyIndexes: file_degrees_v1_payment_service_proto_depIdxs,
		MessageInfos:      file_degrees_v1_payment_service_proto_msgTypes,
	}.Build()
	File_degrees_v1_payment_service_proto = out.File
	file_degrees_v1_payment_service_proto_goTypes = nil
	file_degrees_v1_payment_service_proto_depIdxs = nil
}
