// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: degrees/v1/smtp_service.proto

package p402v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SMTPService_ConfigureSMTP_FullMethodName = "/p402.v1.SMTPService/ConfigureSMTP"
	SMTPService_GetSMTPStatus_FullMethodName = "/p402.v1.SMTPService/GetSMTPStatus"
)

// SMTPServiceClient is the client API for SMTPService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SMTPService provides SMTP configuration management for system administrators
type SMTPServiceClient interface {
	// ConfigureSMTP updates the SMTP configuration
	ConfigureSMTP(ctx context.Context, in *ConfigureSMTPRequest, opts ...grpc.CallOption) (*ConfigureSMTPResponse, error)
	// GetSMTPStatus returns the current SMTP configuration status
	GetSMTPStatus(ctx context.Context, in *GetSMTPStatusRequest, opts ...grpc.CallOption) (*GetSMTPStatusResponse, error)
}

type sMTPServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSMTPServiceClient(cc grpc.ClientConnInterface) SMTPServiceClient {
	return &sMTPServiceClient{cc}
}

func (c *sMTPServiceClient) ConfigureSMTP(ctx context.Context, in *ConfigureSMTPRequest, opts ...grpc.CallOption) (*ConfigureSMTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureSMTPResponse)
	err := c.cc.Invoke(ctx, SMTPService_ConfigureSMTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sMTPServiceClient) GetSMTPStatus(ctx context.Context, in *GetSMTPStatusRequest, opts ...grpc.CallOption) (*GetSMTPStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSMTPStatusResponse)
	err := c.cc.Invoke(ctx, SMTPService_GetSMTPStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SMTPServiceServer is the server API for SMTPService service.
// All implementations should embed UnimplementedSMTPServiceServer
// for forward compatibility.
//
// SMTPService provides SMTP configuration management for system administrators
type SMTPServiceServer interface {
	// ConfigureSMTP updates the SMTP configuration
	ConfigureSMTP(context.Context, *ConfigureSMTPRequest) (*ConfigureSMTPResponse, error)
	// GetSMTPStatus returns the current SMTP configuration status
	GetSMTPStatus(context.Context, *GetSMTPStatusRequest) (*GetSMTPStatusResponse, error)
}

// UnimplementedSMTPServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSMTPServiceServer struct{}

func (UnimplementedSMTPServiceServer) ConfigureSMTP(context.Context, *ConfigureSMTPRequest) (*ConfigureSMTPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigureSMTP not implemented")
}
func (UnimplementedSMTPServiceServer) GetSMTPStatus(context.Context, *GetSMTPStatusRequest) (*GetSMTPStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSMTPStatus not implemented")
}
func (UnimplementedSMTPServiceServer) testEmbeddedByValue() {}

// UnsafeSMTPServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SMTPServiceServer will
// result in compilation errors.
type UnsafeSMTPServiceServer interface {
	mustEmbedUnimplementedSMTPServiceServer()
}

func RegisterSMTPServiceServer(s grpc.ServiceRegistrar, srv SMTPServiceServer) {
	// If the following call panics, it indicates UnimplementedSMTPServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SMTPService_ServiceDesc, srv)
}

func _SMTPService_ConfigureSMTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureSMTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SMTPServiceServer).ConfigureSMTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SMTPService_ConfigureSMTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SMTPServiceServer).ConfigureSMTP(ctx, req.(*ConfigureSMTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SMTPService_GetSMTPStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSMTPStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SMTPServiceServer).GetSMTPStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SMTPService_GetSMTPStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SMTPServiceServer).GetSMTPStatus(ctx, req.(*GetSMTPStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SMTPService_ServiceDesc is the grpc.ServiceDesc for SMTPService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SMTPService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "p402.v1.SMTPService",
	HandlerType: (*SMTPServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConfigureSMTP",
			Handler:    _SMTPService_ConfigureSMTP_Handler,
		},
		{
			MethodName: "GetSMTPStatus",
			Handler:    _SMTPService_GetSMTPStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "degrees/v1/smtp_service.proto",
}
