// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: degrees/v1/smtp_service.proto

package p402v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigureSMTPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SmtpAddress   string                 `protobuf:"bytes,1,opt,name=smtp_address,json=smtpAddress,proto3" json:"smtp_address,omitempty"`
	SmtpPort      int32                  `protobuf:"varint,2,opt,name=smtp_port,json=smtpPort,proto3" json:"smtp_port,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Identity      string                 `protobuf:"bytes,5,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureSMTPRequest) Reset() {
	*x = ConfigureSMTPRequest{}
	mi := &file_degrees_v1_smtp_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureSMTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureSMTPRequest) ProtoMessage() {}

func (x *ConfigureSMTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_smtp_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureSMTPRequest.ProtoReflect.Descriptor instead.
func (*ConfigureSMTPRequest) Descriptor() ([]byte, []int) {
	return file_degrees_v1_smtp_service_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigureSMTPRequest) GetSmtpAddress() string {
	if x != nil {
		return x.SmtpAddress
	}
	return ""
}

func (x *ConfigureSMTPRequest) GetSmtpPort() int32 {
	if x != nil {
		return x.SmtpPort
	}
	return 0
}

func (x *ConfigureSMTPRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ConfigureSMTPRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ConfigureSMTPRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

type ConfigureSMTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureSMTPResponse) Reset() {
	*x = ConfigureSMTPResponse{}
	mi := &file_degrees_v1_smtp_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureSMTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureSMTPResponse) ProtoMessage() {}

func (x *ConfigureSMTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_smtp_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureSMTPResponse.ProtoReflect.Descriptor instead.
func (*ConfigureSMTPResponse) Descriptor() ([]byte, []int) {
	return file_degrees_v1_smtp_service_proto_rawDescGZIP(), []int{1}
}

func (x *ConfigureSMTPResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfigureSMTPResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetSMTPStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSMTPStatusRequest) Reset() {
	*x = GetSMTPStatusRequest{}
	mi := &file_degrees_v1_smtp_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSMTPStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSMTPStatusRequest) ProtoMessage() {}

func (x *GetSMTPStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_smtp_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSMTPStatusRequest.ProtoReflect.Descriptor instead.
func (*GetSMTPStatusRequest) Descriptor() ([]byte, []int) {
	return file_degrees_v1_smtp_service_proto_rawDescGZIP(), []int{2}
}

type GetSMTPStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	SmtpAddress   string                 `protobuf:"bytes,2,opt,name=smtp_address,json=smtpAddress,proto3" json:"smtp_address,omitempty"`
	SmtpPort      int32                  `protobuf:"varint,3,opt,name=smtp_port,json=smtpPort,proto3" json:"smtp_port,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Configured    bool                   `protobuf:"varint,5,opt,name=configured,proto3" json:"configured,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSMTPStatusResponse) Reset() {
	*x = GetSMTPStatusResponse{}
	mi := &file_degrees_v1_smtp_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSMTPStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSMTPStatusResponse) ProtoMessage() {}

func (x *GetSMTPStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_degrees_v1_smtp_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSMTPStatusResponse.ProtoReflect.Descriptor instead.
func (*GetSMTPStatusResponse) Descriptor() ([]byte, []int) {
	return file_degrees_v1_smtp_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetSMTPStatusResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *GetSMTPStatusResponse) GetSmtpAddress() string {
	if x != nil {
		return x.SmtpAddress
	}
	return ""
}

func (x *GetSMTPStatusResponse) GetSmtpPort() int32 {
	if x != nil {
		return x.SmtpPort
	}
	return 0
}

func (x *GetSMTPStatusResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetSMTPStatusResponse) GetConfigured() bool {
	if x != nil {
		return x.Configured
	}
	return false
}

var File_degrees_v1_smtp_service_proto protoreflect.FileDescriptor

const file_degrees_v1_smtp_service_proto_rawDesc = "" +
	"\n" +
	"\x1ddegrees/v1/smtp_service.proto\x12\ap402.v1\x1a\x1cgoogle/api/annotations.proto\"\xaa\x01\n" +
	"\x14ConfigureSMTPRequest\x12!\n" +
	"\fsmtp_address\x18\x01 \x01(\tR\vsmtpAddress\x12\x1b\n" +
	"\tsmtp_port\x18\x02 \x01(\x05R\bsmtpPort\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x1a\n" +
	"\bidentity\x18\x05 \x01(\tR\bidentity\"K\n" +
	"\x15ConfigureSMTPResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x16\n" +
	"\x14GetSMTPStatusRequest\"\xa9\x01\n" +
	"\x15GetSMTPStatusResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12!\n" +
	"\fsmtp_address\x18\x02 \x01(\tR\vsmtpAddress\x12\x1b\n" +
	"\tsmtp_port\x18\x03 \x01(\x05R\bsmtpPort\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1e\n" +
	"\n" +
	"configured\x18\x05 \x01(\bR\n" +
	"configured2\xf6\x01\n" +
	"\vSMTPService\x12t\n" +
	"\rConfigureSMTP\x12\x1d.p402.v1.ConfigureSMTPRequest\x1a\x1e.p402.v1.ConfigureSMTPResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\x1a\x19/api/v1/admin/smtp/config\x12q\n" +
	"\rGetSMTPStatus\x12\x1d.p402.v1.GetSMTPStatusRequest\x1a\x1e.p402.v1.GetSMTPStatusResponse\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v1/admin/smtp/statusB\x9c\x01\n" +
	"\vcom.p402.v1B\x10SmtpServiceProtoP\x01Z>github.com/richardbowden/degrees/internal/pb/degrees/v1;p402v1\xa2\x02\x03PXX\xaa\x02\aP402.V1\xca\x02\aP402\\V1\xe2\x02\x13P402\\V1\\GPBMetadata\xea\x02\bP402::V1b\x06proto3"

var (
	file_degrees_v1_smtp_service_proto_rawDescOnce sync.Once
	file_degrees_v1_smtp_service_proto_rawDescData []byte
)

func file_degrees_v1_smtp_service_proto_rawDescGZIP() []byte {
	file_degrees_v1_smtp_service_proto_rawDescOnce.Do(func() {
		file_degrees_v1_smtp_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_degrees_v1_smtp_service_proto_rawDesc), len(file_degrees_v1_smtp_service_proto_rawDesc)))
	})
	return file_degrees_v1_smtp_service_proto_rawDescData
}

var file_degrees_v1_smtp_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_degrees_v1_smtp_service_proto_goTypes = []any{
	(*ConfigureSMTPRequest)(nil),  // 0: p402.v1.ConfigureSMTPRequest
	(*ConfigureSMTPResponse)(nil), // 1: p402.v1.ConfigureSMTPResponse
	(*GetSMTPStatusRequest)(nil),  // 2: p402.v1.GetSMTPStatusRequest
	(*GetSMTPStatusResponse)(nil), // 3: p402.v1.GetSMTPStatusResponse
}
var file_degrees_v1_smtp_service_proto_depIdxs = []int32{
	0, // 0: p402.v1.SMTPService.ConfigureSMTP:input_type -> p402.v1.ConfigureSMTPRequest
	2, // 1: p402.v1.SMTPService.GetSMTPStatus:input_type -> p402.v1.GetSMTPStatusRequest
	1, // 2: p402.v1.SMTPService.ConfigureSMTP:output_type -> p402.v1.ConfigureSMTPResponse
	3, // 3: p402.v1.SMTPService.GetSMTPStatus:output_type -> p402.v1.GetSMTPStatusResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_degrees_v1_smtp_service_proto_init() }
func file_degrees_v1_smtp_service_proto_init() {
	if File_degrees_v1_smtp_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_degrees_v1_smtp_service_proto_rawDesc), len(file_degrees_v1_smtp_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_degrees_v1_smtp_service_proto_goTypes,
		DependencyIndexes: file_degrees_v1_smtp_service_proto_depIdxs,
		MessageInfos:      file_degrees_v1_smtp_service_proto_msgTypes,
	}.Build()
	File_degrees_v1_smtp_service_proto = out.File
	file_degrees_v1_smtp_service_proto_goTypes = nil
	file_degrees_v1_smtp_service_proto_depIdxs = nil
}
